var fM = Uint8Array
    , fN = Uint16Array
    , fO = Int32Array
    ,
    fP = new fM([0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x1, 0x1, 0x1, 0x2, 0x2, 0x2, 0x2, 0x3, 0x3, 0x3, 0x3, 0x4, 0x4, 0x4, 0x4, 0x5, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0])
    ,
    fQ = new fM([0x0, 0x0, 0x0, 0x0, 0x1, 0x1, 0x2, 0x2, 0x3, 0x3, 0x4, 0x4, 0x5, 0x5, 0x6, 0x6, 0x7, 0x7, 0x8, 0x8, 0x9, 0x9, 0xa, 0xa, 0xb, 0xb, 0xc, 0xc, 0xd, 0xd, 0x0, 0x0])
    , fR = new fM([0x10, 0x11, 0x12, 0x0, 0x8, 0x7, 0x9, 0x6, 0xa, 0x5, 0xb, 0x4, 0xc, 0x3, 0xd, 0x2, 0xe, 0x1, 0xf])
    , fS = function (id, ig) {
        for (var ih = new fN(0x1f), ij = 0x0; ij < 0x1f; ++ij)
            ih[ij] = ig += 0x1 << id[ij - 0x1];
        var ik = new fO(ih[0x1e]);
        for (ij = 0x1; ij < 0x1e; ++ij)
            for (var il = ih[ij]; il < ih[ij + 0x1]; ++il)
                ik[il] = il - ih[ij] << 0x5 | ij;
        return {
            'b': ih,
            'r': ik
        };
    }
    , fT = fS(fP, 0x2)
    , fU = fT['b']
    , fV = fT['r'];
fU[0x1c] = 0x102,
    fV[0x102] = 0x1c;
for (var fW = fS(fQ, 0x0)['r'], fX = new fN(0x8000), fY = 0x0; fY < 0x8000; ++fY) {
    var fZ = (0xaaaa & fY) >> 0x1 | (0x5555 & fY) << 0x1;
    fZ = (0xf0f0 & (fZ = (0xcccc & fZ) >> 0x2 | (0x3333 & fZ) << 0x2)) >> 0x4 | (0xf0f & fZ) << 0x4,
        fX[fY] = ((0xff00 & fZ) >> 0x8 | (0xff & fZ) << 0x8) >> 0x1;
}
var g0 = function (id, ig, ih) {
    for (var ij = id['length'], ik = 0x0, il = new fN(ig); ik < ij; ++ik)
        id[ik] && ++il[id[ik] - 0x1];
    var im, ip = new fN(ig);
    for (ik = 0x1; ik < ig; ++ik)
        ip[ik] = ip[ik - 0x1] + il[ik - 0x1] << 0x1;
    if (ih) {
        im = new fN(0x1 << ig);
        var iq = 0xf - ig;
        for (ik = 0x0; ik < ij; ++ik)
            if (id[ik]) {
                for (var is = ik << 0x4 | id[ik], iu = ig - id[ik], iv = ip[id[ik] - 0x1]++ << iu, iw = iv | (0x1 << iu) - 0x1; iv <= iw; ++iv)
                    im[fX[iv] >> iq] = is;
            }
    } else {
        for (im = new fN(ij),
                 ik = 0x0; ik < ij; ++ik)
            id[ik] && (im[ik] = fX[ip[id[ik] - 0x1]++] >> 0xf - id[ik]);
    }
    return im;
}
    , g1 = new fM(0x120);
for (fY = 0x0; fY < 0x90; ++fY)
    g1[fY] = 0x8;
for (fY = 0x90; fY < 0x100; ++fY)
    g1[fY] = 0x9;
for (fY = 0x100; fY < 0x118; ++fY)
    g1[fY] = 0x7;
for (fY = 0x118; fY < 0x120; ++fY)
    g1[fY] = 0x8;
var g2 = new fM(0x20);
for (fY = 0x0; fY < 0x20; ++fY)
    g2[fY] = 0x5;
var g3 = g0(g1, 0x9, 0x0)
    , g4 = g0(g2, 0x5, 0x0)
    , g5 = function (id) {
    return (id + 0x7) / 0x8 | 0x0;
}
    , g6 = function (id, ig, ih) {
    return (null == ih || ih > id['length']) && (ih = id['length']),
        new fM(id['subarray'](ig, ih));
}
    , g7 = function (id, ig, ih) {
    ih <<= 0x7 & ig;
    var ij = ig / 0x8 | 0x0;
    id[ij] |= ih,
        id[ij + 0x1] |= ih >> 0x8;
}
    , g8 = function (id, ig, ih) {
    ih <<= 0x7 & ig;
    var ij = ig / 0x8 | 0x0;
    id[ij] |= ih,
        id[ij + 0x1] |= ih >> 0x8,
        id[ij + 0x2] |= ih >> 0x10;
}
    , g9 = function (id, ig) {
    for (var ih = [], ij = 0x0; ij < id['length']; ++ij)
        id[ij] && ih['push']({
            's': ij,
            'f': id[ij]
        });
    var ik = ih['length']
        , il = ih['slice']();
    if (!ik)
        return {
            't': gj,
            'l': 0x0
        };
    if (0x1 == ik) {
        var im = new fM(ih[0x0]['s'] + 0x1);
        return im[ih[0x0]['s']] = 0x1,
            {
                't': im,
                'l': 0x1
            };
    }
    ih['sort'](function (iF, iG) {
        return iF['f'] - iG['f'];
    }),
        ih['push']({
            's': -0x1,
            'f': 0x61a9
        });
    var ip = ih[0x0]
        , iq = ih[0x1]
        , is = 0x0
        , iu = 0x1
        , iv = 0x2;
    for (ih[0x0] = {
        's': -0x1,
        'f': ip['f'] + iq['f'],
        'l': ip,
        'r': iq
    }; iu != ik - 0x1;)
        ip = ih[ih[is]['f'] < ih[iv]['f'] ? is++ : iv++],
            iq = ih[is != iu && ih[is]['f'] < ih[iv]['f'] ? is++ : iv++],
            ih[iu++] = {
                's': -0x1,
                'f': ip['f'] + iq['f'],
                'l': ip,
                'r': iq
            };
    var iw = il[0x0]['s'];
    for (ij = 0x1; ij < ik; ++ij)
        il[ij]['s'] > iw && (iw = il[ij]['s']);
    var ix = new fN(iw + 0x1)
        , iy = ga(ih[iu - 0x1], ix, 0x0);
    if (iy > ig) {
        ij = 0x0;
        var iz = 0x0
            , iA = iy - ig
            , iB = 0x1 << iA;
        for (il['sort'](function (iF, iG) {
            return ix[iG['s']] - ix[iF['s']] || iF['f'] - iG['f'];
        }); ij < ik; ++ij) {
            var iC = il[ij]['s'];
            if (!(ix[iC] > ig))
                break;
            iz += iB - (0x1 << iy - ix[iC]),
                ix[iC] = ig;
        }
        for (iz >>= iA; iz > 0x0;) {
            var iD = il[ij]['s'];
            ix[iD] < ig ? iz -= 0x1 << ig - ix[iD]++ - 0x1 : ++ij;
        }
        for (; ij >= 0x0 && iz; --ij) {
            var iE = il[ij]['s'];
            ix[iE] == ig && (--ix[iE],
                ++iz);
        }
        iy = ig;
    }
    return {
        't': new fM(ix),
        'l': iy
    };
}
    , ga = function (id, ig, ih) {
    return -0x1 == id['s'] ? Math['max'](ga(id['l'], ig, ih + 0x1), ga(id['r'], ig, ih + 0x1)) : ig[id['s']] = ih;
}
    , gb = function (id) {
    for (var ig = id['length']; ig && !id[--ig];)
        ;
    for (var ih = new fN(++ig), ij = 0x0, ik = id[0x0], il = 0x1, im = function (iq) {
        ih[ij++] = iq;
    }, ip = 0x1; ip <= ig; ++ip)
        if (id[ip] == ik && ip != ig)
            ++il;
        else {
            if (!ik && il > 0x2) {
                for (; il > 0x8a; il -= 0x8a)
                    im(0x7ff2);
                il > 0x2 && (im(il > 0xa ? il - 0xb << 0x5 | 0x7012 : il - 0x3 << 0x5 | 0x3011),
                    il = 0x0);
            } else {
                if (il > 0x3) {
                    for (im(ik),
                             --il; il > 0x6; il -= 0x6)
                        im(0x2070);
                    il > 0x2 && (im(il - 0x3 << 0x5 | 0x2010),
                        il = 0x0);
                }
            }
            for (; il--;)
                im(ik);
            il = 0x1,
                ik = id[ip];
        }
    return {
        'c': ih['subarray'](0x0, ij),
        'n': ig
    };
}
    , gd = function (id, ig) {
    for (var ih = 0x0, ij = 0x0; ij < ig['length']; ++ij)
        ih += id[ij] * ig[ij];
    return ih;
}
    , gf = function (id, ig, ih) {
    var ij = ih['length']
        , ik = g5(ig + 0x2);
    id[ik] = 0xff & ij,
        id[ik + 0x1] = ij >> 0x8,
        id[ik + 0x2] = 0xff ^ id[ik],
        id[ik + 0x3] = 0xff ^ id[ik + 0x1];
    for (var il = 0x0; il < ij; ++il)
        id[ik + il + 0x4] = ih[il];
    return 0x8 * (ik + 0x4 + ij);
}
    , gg = function (id, ig, ih, ij, ik, il, im, ip, iq, is, iu) {
    g7(ig, iu++, ih),
        ++ik[0x100];
    for (var iv = g9(ik, 0xf), iw = iv['t'], ix = iv['l'], iy = g9(il, 0xf), iz = iy['t'], iA = iy['l'], iB = gb(iw), iC = iB['c'], iD = iB['n'], iE = gb(iz), iF = iE['c'], iG = iE['n'], iH = new fN(0x13), iI = 0x0; iI < iC['length']; ++iI)
        ++iH[0x1f & iC[iI]];
    for (iI = 0x0; iI < iF['length']; ++iI)
        ++iH[0x1f & iF[iI]];
    for (var iJ = g9(iH, 0x7), iK = iJ['t'], iL = iJ['l'], iM = 0x13; iM > 0x4 && !iK[fR[iM - 0x1]]; --iM)
        ;
    var iN, iO, iP, iQ, iR = is + 0x5 << 0x3, iS = gd(ik, g1) + gd(il, g2) + im,
        iT = gd(ik, iw) + gd(il, iz) + im + 0xe + 0x3 * iM + gd(iH, iK) + 0x2 * iH[0x10] + 0x3 * iH[0x11] + 0x7 * iH[0x12];
    if (iq >= 0x0 && iR <= iS && iR <= iT)
        return gf(ig, iu, id['subarray'](iq, iq + is));
    if (g7(ig, iu, 0x1 + (iT < iS)),
        iu += 0x2,
    iT < iS) {
        iN = g0(iw, ix, 0x0),
            iO = iw,
            iP = g0(iz, iA, 0x0),
            iQ = iz;
        var iU = g0(iK, iL, 0x0);
        g7(ig, iu, iD - 0x101),
            g7(ig, iu + 0x5, iG - 0x1),
            g7(ig, iu + 0xa, iM - 0x4),
            iu += 0xe;
        for (iI = 0x0; iI < iM; ++iI)
            g7(ig, iu + 0x3 * iI, iK[fR[iI]]);
        iu += 0x3 * iM;
        for (var iV = [iC, iF], iW = 0x0; iW < 0x2; ++iW) {
            var iX = iV[iW];
            for (iI = 0x0; iI < iX['length']; ++iI) {
                var iY = 0x1f & iX[iI];
                g7(ig, iu, iU[iY]),
                    iu += iK[iY],
                iY > 0xf && (g7(ig, iu, iX[iI] >> 0x5 & 0x7f),
                    iu += iX[iI] >> 0xc);
            }
        }
    } else
        iN = g3,
            iO = g1,
            iP = g4,
            iQ = g2;
    for (iI = 0x0; iI < ip; ++iI) {
        var iZ = ij[iI];
        if (iZ > 0xff) {
            g8(ig, iu, iN[(iY = iZ >> 0x12 & 0x1f) + 0x101]),
                iu += iO[iY + 0x101],
            iY > 0x7 && (g7(ig, iu, iZ >> 0x17 & 0x1f),
                iu += fP[iY]);
            var j0 = 0x1f & iZ;
            g8(ig, iu, iP[j0]),
                iu += iQ[j0],
            j0 > 0x3 && (g8(ig, iu, iZ >> 0x5 & 0x1fff),
                iu += fQ[j0]);
        } else
            g8(ig, iu, iN[iZ]),
                iu += iO[iZ];
    }
    return g8(ig, iu, iN[0x100]),
    iu + iO[0x100];
}
    , gh = new fO([0x10004, 0x20008, 0x20010, 0x20020, 0x40020, 0x100080, 0x100100, 0x204400, 0x205000])
    , gj = new fM(0x0)
    , gk = (function () {
    for (var id = new Int32Array(0x100), ig = 0x0; ig < 0x100; ++ig) {
        for (var ih = ig, ij = 0x9; --ij;)
            ih = (0x1 & ih && -0x12477ce0) ^ ih >>> 0x1;
        id[ig] = ih;
    }
    return id;
}())
    , gl = function (id, ig, ih, ij, ik) {
    if (!ik && (ik = {
        'l': 0x1
    },
        ig['dictionary'])) {
        var il = ig['dictionary']['subarray'](-0x8000)
            , im = new fM(il['length'] + id['length']);
        im['set'](il),
            im['set'](id, il['length']),
            id = im,
            ik['w'] = il['length'];
    }
    return function (ip, iq, is, iu, iv, iw) {
        var ix = iw['z'] || ip['length']
            , iy = new fM(iu + ix + 0x5 * (0x1 + Math['ceil'](ix / 0x1b58)) + iv)
            , iz = iy['subarray'](iu, iy['length'] - iv)
            , iA = iw['l']
            , iB = 0x7 & (iw['r'] || 0x0);
        if (iq) {
            iB && (iz[0x0] = iw['r'] >> 0x3);
            for (var iC = gh[iq - 0x1], iD = iC >> 0xd, iE = 0x1fff & iC, iF = (0x1 << is) - 0x1, iG = iw['p'] || new fN(0x8000), iH = iw['h'] || new fN(iF + 0x1), iI = Math['ceil'](is / 0x3), iJ = 0x2 * iI, iK = function (jg) {
                return (ip[jg] ^ ip[jg + 0x1] << iI ^ ip[jg + 0x2] << iJ) & iF;
            }, iL = new fO(0x61a8), iM = new fN(0x120), iN = new fN(0x20), iO = 0x0, iP = 0x0, iQ = iw['i'] || 0x0, iR = 0x0, iS = iw['w'] || 0x0, iT = 0x0; iQ + 0x2 < ix; ++iQ) {
                var iU = iK(iQ)
                    , iV = 0x7fff & iQ
                    , iW = iH[iU];
                if (iG[iV] = iW,
                    iH[iU] = iV,
                iS <= iQ) {
                    var iX = ix - iQ;
                    if ((iO > 0x1b58 || iR > 0x6000) && (iX > 0x1a7 || !iA)) {
                        iB = gg(ip, iz, 0x0, iL, iM, iN, iP, iR, iT, iQ - iT, iB),
                            iR = iO = iP = 0x0,
                            iT = iQ;
                        for (var iY = 0x0; iY < 0x11e; ++iY)
                            iM[iY] = 0x0;
                        for (iY = 0x0; iY < 0x1e; ++iY)
                            iN[iY] = 0x0;
                    }
                    var iZ = 0x2
                        , j0 = 0x0
                        , j1 = iE
                        , j2 = iV - iW & 0x7fff;
                    if (iX > 0x2 && iU == iK(iQ - j2))
                        for (var j3 = Math['min'](iD, iX) - 0x1, j4 = Math['min'](0x7fff, iQ), j5 = Math['min'](0x102, iX); j2 <= j4 && --j1 && iV != iW;) {
                            if (ip[iQ + iZ] == ip[iQ + iZ - j2]) {
                                for (var j6 = 0x0; j6 < j5 && ip[iQ + j6] == ip[iQ + j6 - j2]; ++j6)
                                    ;
                                if (j6 > iZ) {
                                    if (iZ = j6,
                                        j0 = j2,
                                    j6 > j3)
                                        break;
                                    var j7 = Math['min'](j2, j6 - 0x2)
                                        , j8 = 0x0;
                                    for (iY = 0x0; iY < j7; ++iY) {
                                        var j9 = iQ - j2 + iY & 0x7fff
                                            , ja = j9 - iG[j9] & 0x7fff;
                                        ja > j8 && (j8 = ja,
                                            iW = j9);
                                    }
                                }
                            }
                            j2 += (iV = iW) - (iW = iG[iV]) & 0x7fff;
                        }
                    if (j0) {
                        iL[iR++] = 0x10000000 | fV[iZ] << 0x12 | fW[j0];
                        var jb = 0x1f & fV[iZ]
                            , jd = 0x1f & fW[j0];
                        iP += fP[jb] + fQ[jd],
                            ++iM[0x101 + jb],
                            ++iN[jd],
                            iS = iQ + iZ,
                            ++iO;
                    } else
                        iL[iR++] = ip[iQ],
                            ++iM[ip[iQ]];
                }
            }
            for (iQ = Math['max'](iQ, iS); iQ < ix; ++iQ)
                iL[iR++] = ip[iQ],
                    ++iM[ip[iQ]];
            iB = gg(ip, iz, iA, iL, iM, iN, iP, iR, iT, iQ - iT, iB),
            iA || (iw['r'] = 0x7 & iB | iz[iB / 0x8 | 0x0] << 0x3,
                iB -= 0x7,
                iw['h'] = iH,
                iw['p'] = iG,
                iw['i'] = iQ,
                iw['w'] = iS);
        } else {
            for (iQ = iw['w'] || 0x0; iQ < ix + iA; iQ += 0xffff) {
                var jf = iQ + 0xffff;
                jf >= ix && (iz[iB / 0x8 | 0x0] = iA,
                    jf = ix),
                    iB = gf(iz, iB + 0x1, ip['subarray'](iQ, jf));
            }
            iw['i'] = ix;
        }
        return g6(iy, 0x0, iu + g5(iB) + iv);
    }(id, null == ig['level'] ? 0x6 : ig['level'], null == ig['mem'] ? Math['ceil'](1.5 * Math['max'](0x8, Math['min'](0xd, Math['log'](id['length'])))) : 0xc + ig['mem'], ih, ij, ik);
}
    , gm = function (id, ig, ih) {
    for (; ih; ++ig)
        id[ig] = ih,
            ih >>>= 0x8;
};

function gp(id, ig) {
    ig || (ig = {});
    var ih = (function () {
        var ip = -0x1;
        return {
            'p': function (iq) {
                for (var is = ip, iu = 0x0; iu < iq['length']; ++iu)
                    is = gk[0xff & is ^ iq[iu]] ^ is >>> 0x8;
                ip = is;
            },
            'd': function () {
                return ~ip;
            }
        };
    }())
        , ij = id['length'];
    ih['p'](id);
    var ik, il = gl(id, ig, 0xa + ((ik = ig)['filename'] ? ik['filename']['length'] + 0x1 : 0x0), 0x8),
        im = il['length'];
    return function (ip, iq) {
        var is = iq['filename'];
        if (ip[0x0] = 0x1f,
            ip[0x1] = 0x8b,
            ip[0x2] = 0x8,
            ip[0x8] = iq['level'] < 0x2 ? 0x4 : 0x9 == iq['level'] ? 0x2 : 0x0,
            ip[0x9] = 0x3,
        0x0 != iq['mtime'] && gm(ip, 0x4, Math['floor'](new Date(iq['mtime'] || Date['now']()) / 0x3e8)),
            is) {
            ip[0x3] = 0x8;
            for (var iu = 0x0; iu <= is['length']; ++iu)
                ip[iu + 0xa] = is['charCodeAt'](iu);
        }
    }(il, ig),
        gm(il, im - 0x8, ih['d']()),
        gm(il, im - 0x4, ij),
        il;
}

var gq = 'undefined' != typeof TextEncoder && new TextEncoder()
    , gs = 'undefined' != typeof TextDecoder && new TextDecoder();
try {
    gs['decode'](gj, {
        'stream': !0x0
    }),
        0x1;
} catch (id) {
}

const gu = ig => {
    const ih = function (iq, is) {
        if (gq)
            return gq['encode'](iq);
        for (var iu = iq['length'], iv = new fM(iq['length'] + (iq['length'] >> 0x1)), iw = 0x0, ix = function (iB) {
            iv[iw++] = iB;
        }, iy = 0x0; iy < iu; ++iy) {
            if (iw + 0x5 > iv['length']) {
                var iz = new fM(iw + 0x8 + (iu - iy << 0x1));
                iz['set'](iv),
                    iv = iz;
            }
            var iA = iq['charCodeAt'](iy);
            iA < 0x80 || is ? ix(iA) : iA < 0x800 ? (ix(0xc0 | iA >> 0x6),
                ix(0x80 | 0x3f & iA)) : iA > 0xd7ff && iA < 0xe000 ? (ix(0xf0 | (iA = 0x10000 + (0xffc00 & iA) | 0x3ff & iq['charCodeAt'](++iy)) >> 0x12),
                ix(0x80 | iA >> 0xc & 0x3f),
                ix(0x80 | iA >> 0x6 & 0x3f),
                ix(0x80 | 0x3f & iA)) : (ix(0xe0 | iA >> 0xc),
                ix(0x80 | iA >> 0x6 & 0x3f),
                ix(0x80 | 0x3f & iA));
        }
        return g6(iv, 0x0, iw);
    }(JSON['stringify'](ig))
        , ij = gp(ih)
        , ik = 0x2 + ij['length']
        , il = new ArrayBuffer(ik)
        , im = new Uint8Array(il);
    let ip = 0x0;
    im[ip++] = 0x1,
        im[ip++] = 0x4;
    for (let iq = 0x0; iq < ij['length']; ++iq)
        im[ip++] = ij[iq] ^ iq + 0x4;
    return im;
}

function typedArrayToBase64(input) {
    if (input instanceof ArrayBuffer ||
        typeof SharedArrayBuffer !== 'undefined' &&
        input instanceof SharedArrayBuffer) {
        return Buffer.from(input).toString('base64');
    }

    if (ArrayBuffer.isView(input)) {
        return Buffer.from(
            input.buffer,
            input.byteOffset,
            input.byteLength
        ).toString('base64');
    }

    throw new TypeError(
        'input 必须是 TypedArray、DataView、ArrayBuffer 或 Buffer'
    );
}
let config_fp = {
    "lng": "zh-cn",
    "h": "6a8d0e47a2d485ea4fa89c7b|63f9fb3c08a953dbada26400adc14086f9da5907987272c52cc041967e90b392",
    "cs": {
        "CF0100": false,
        "CF0101": true,
        "CF0102": {
            "depth": 3559,
            "msg": "Maximum call stack size exceeded",
            "name": "RangeError",
            "length": 954
        },
        "CF0103": true,
        "CF0104": false,
        "CF0105": 32,
        "CF0106": 1787629133577,
        "CF0107": false,
        "CF0108": -480,
        "CF0109": false,
        "CF0110": {
            "state": "prompt",
            "permission": "default"
        },
        "CF0111": [
            "zh-CN",
            "en",
            "en-GB",
            "en-US"
        ],
        "CF0112": false,
        "CF0113": false,
        "CF0114": [
            "Google Inc. (Microsoft)",
            "ANGLE (Microsoft, Microsoft Basic Render Driver (0x0000008C) Direct3D11 vs_5_0 ps_5_0, D3D11)",
            "WebKit",
            "WebKit WebGL",
            "WebGL 1.0 (OpenGL ES 2.0 Chromium)"
        ],
        "CF0115": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0",
        "CF0116": {
            "brands": [
                {
                    "brand": "Not=A?Brand",
                    "version": "99"
                },
                {
                    "brand": "Microsoft Edge",
                    "version": "151"
                },
                {
                    "brand": "Chromium",
                    "version": "151"
                }
            ],
            "mobile": false,
            "platform": "Windows"
        },
        "CF0117": "Google Inc.",
        "CF0118": "Win32",
        "CF0119": "20030107",
        "CF0120": {
            "width": 1536,
            "height": 864,
            "availW": 1536,
            "availH": 824,
            "clrDepth": 24,
            "pxDepth": 24,
            "pxRatio": 1.25,
            "outerW": 1536,
            "outerH": 824
        },
        "CF0121": [
            "Google Inc. (Microsoft)",
            "ANGLE (Microsoft, Microsoft Basic Render Driver (0x0000008C) Direct3D11 vs_5_0 ps_5_0, D3D11)"
        ],
        "CF0122": {
            "ogg": "",
            "h264": "probably",
            "webm": "probably"
        },
        "CF0123": true,
        "CF0124": [
            "PDF Viewer:Portable Document Format:internal-pdf-viewer",
            "Chrome PDF Viewer:Portable Document Format:internal-pdf-viewer",
            "Chromium PDF Viewer:Portable Document Format:internal-pdf-viewer",
            "Microsoft Edge PDF Viewer:Portable Document Format:internal-pdf-viewer",
            "WebKit built-in PDF:Portable Document Format:internal-pdf-viewer"
        ],
        "CF0125": true,
        "CF0126": [
            "Portable Document Format~application/pdf~pdf",
            "Portable Document Format~text/pdf~pdf"
        ],
        "CF0127": true,
        "CF0128": "function close() { [native code] }",
        "CF0129": "[object External]",
        "CF0130": [
            "Object",
            "Function",
            "Array",
            "Number",
            "parseFloat",
            "parseInt",
            "Infinity",
            "NaN",
            "undefined",
            "Boolean",
            "String",
            "Symbol",
            "Date",
            "Promise",
            "RegExp",
            "Error",
            "AggregateError",
            "EvalError",
            "RangeError",
            "ReferenceError",
            "SyntaxError",
            "TypeError",
            "URIError",
            "globalThis",
            "JSON",
            "Math",
            "Intl",
            "ArrayBuffer",
            "Atomics",
            "Uint8Array",
            "Int8Array",
            "Uint16Array",
            "Int16Array",
            "Uint32Array",
            "Int32Array",
            "BigUint64Array",
            "BigInt64Array",
            "Uint8ClampedArray",
            "Float32Array",
            "Float64Array",
            "DataView",
            "Map",
            "BigInt",
            "Set",
            "Iterator",
            "WeakMap",
            "WeakSet",
            "Proxy",
            "Reflect",
            "FinalizationRegistry",
            "WeakRef",
            "decodeURI",
            "decodeURIComponent",
            "encodeURI",
            "encodeURIComponent",
            "escape",
            "unescape",
            "eval",
            "isFinite",
            "isNaN",
            "console",
            "Option",
            "Image",
            "Audio",
            "webkitURL",
            "webkitRTCPeerConnection",
            "webkitMediaStream",
            "WebKitMutationObserver",
            "WebKitCSSMatrix",
            "XPathResult",
            "XPathExpression",
            "XPathEvaluator",
            "XMLSerializer",
            "XMLHttpRequestUpload",
            "XMLHttpRequestEventTarget",
            "XMLHttpRequest",
            "XMLDocument",
            "WritableStreamDefaultWriter",
            "WritableStreamDefaultController",
            "WritableStream",
            "Worker",
            "WindowControlsOverlayGeometryChangeEvent",
            "WindowControlsOverlay",
            "Window",
            "WheelEvent",
            "WebSocket",
            "WebGLVertexArrayObject",
            "WebGLUniformLocation",
            "WebGLTransformFeedback",
            "WebGLTexture",
            "WebGLSync",
            "WebGLShaderPrecisionFormat",
            "WebGLShader",
            "WebGLSampler",
            "WebGLRenderingContext",
            "WebGLRenderbuffer",
            "WebGLQuery",
            "WebGLProgram",
            "WebGLObject",
            "WebGLFramebuffer",
            "WebGLContextEvent",
            "WebGLBuffer",
            "WebGLActiveInfo",
            "WebGL2RenderingContext",
            "WaveShaperNode",
            "VisualViewport",
            "VisibilityStateEntry",
            "VirtualKeyboardGeometryChangeEvent",
            "ViewTransitionTypeSet",
            "ViewTransition",
            "ViewTimeline",
            "VideoPlaybackQuality",
            "VideoFrame",
            "VideoColorSpace",
            "ValidityState",
            "VTTCue",
            "UserActivation",
            "URLSearchParams",
            "URLPattern",
            "URL",
            "UIEvent",
            "TrustedTypePolicyFactory",
            "TrustedTypePolicy",
            "TrustedScriptURL",
            "TrustedScript",
            "TrustedHTML",
            "TreeWalker",
            "TransitionEvent",
            "TransformStreamDefaultController",
            "TransformStream",
            "TrackEvent",
            "TouchList",
            "TouchEvent",
            "Touch",
            "ToggleEvent",
            "TimeRanges",
            "TextUpdateEvent",
            "TextTrackList",
            "TextTrackCueList",
            "TextTrackCue",
            "TextTrack",
            "TextMetrics",
            "TextFormatUpdateEvent",
            "TextFormat",
            "TextEvent",
            "TextEncoderStream",
            "TextEncoder",
            "TextDecoderStream",
            "TextDecoder",
            "Text",
            "TaskSignal",
            "TaskPriorityChangeEvent",
            "TaskController",
            "TaskAttributionTiming",
            "SyncManager",
            "Subscriber",
            "SubmitEvent",
            "StyleSheetList",
            "StyleSheet",
            "StylePropertyMapReadOnly",
            "StylePropertyMap",
            "StorageEvent",
            "Storage",
            "StereoPannerNode",
            "StaticRange",
            "SourceBufferList",
            "SourceBuffer",
            "ShadowRoot",
            "Selection",
            "SecurityPolicyViolationEvent",
            "ScrollTimeline",
            "ScriptProcessorNode",
            "ScreenOrientation",
            "Screen",
            "Scheduling",
            "Scheduler",
            "SVGViewElement",
            "SVGUseElement",
            "SVGUnitTypes",
            "SVGTransformList",
            "SVGTransform",
            "SVGTitleElement",
            "SVGTextPositioningElement",
            "SVGTextPathElement",
            "SVGTextElement",
            "SVGTextContentElement",
            "SVGTSpanElement",
            "SVGSymbolElement",
            "SVGSwitchElement",
            "SVGStyleElement",
            "SVGStringList",
            "SVGStopElement",
            "SVGSetElement",
            "SVGScriptElement",
            "SVGSVGElement",
            "SVGRectElement",
            "SVGRect",
            "SVGRadialGradientElement",
            "SVGPreserveAspectRatio",
            "SVGPolylineElement",
            "SVGPolygonElement",
            "SVGPointList",
            "SVGPoint",
            "SVGPatternElement",
            "SVGPathElement",
            "SVGNumberList",
            "SVGNumber",
            "SVGMetadataElement",
            "SVGMatrix",
            "SVGMaskElement",
            "SVGMarkerElement",
            "SVGMPathElement",
            "SVGLinearGradientElement",
            "SVGLineElement",
            "SVGLengthList",
            "SVGLength",
            "SVGImageElement",
            "SVGGraphicsElement",
            "SVGGradientElement",
            "SVGGeometryElement",
            "SVGGElement",
            "SVGForeignObjectElement",
            "SVGFilterElement",
            "SVGFETurbulenceElement",
            "SVGFETileElement",
            "SVGFESpotLightElement",
            "SVGFESpecularLightingElement",
            "SVGFEPointLightElement",
            "SVGFEOffsetElement",
            "SVGFEMorphologyElement",
            "SVGFEMergeNodeElement",
            "SVGFEMergeElement",
            "SVGFEImageElement",
            "SVGFEGaussianBlurElement",
            "SVGFEFuncRElement",
            "SVGFEFuncGElement",
            "SVGFEFuncBElement",
            "SVGFEFuncAElement",
            "SVGFEFloodElement",
            "SVGFEDropShadowElement",
            "SVGFEDistantLightElement",
            "SVGFEDisplacementMapElement",
            "SVGFEDiffuseLightingElement",
            "SVGFEConvolveMatrixElement",
            "SVGFECompositeElement",
            "SVGFEComponentTransferElement",
            "SVGFEColorMatrixElement",
            "SVGFEBlendElement",
            "SVGEllipseElement",
            "SVGElement",
            "SVGDescElement",
            "SVGDefsElement",
            "SVGComponentTransferFunctionElement",
            "SVGClipPathElement",
            "SVGCircleElement",
            "SVGAnimationElement",
            "SVGAnimatedTransformList",
            "SVGAnimatedString",
            "SVGAnimatedRect",
            "SVGAnimatedPreserveAspectRatio",
            "SVGAnimatedNumberList",
            "SVGAnimatedNumber",
            "SVGAnimatedLengthList",
            "SVGAnimatedLength",
            "SVGAnimatedInteger",
            "SVGAnimatedEnumeration",
            "SVGAnimatedBoolean",
            "SVGAnimatedAngle",
            "SVGAnimateTransformElement",
            "SVGAnimateMotionElement",
            "SVGAnimateElement",
            "SVGAngle",
            "SVGAElement",
            "Response",
            "ResizeObserverSize",
            "ResizeObserverEntry",
            "ResizeObserver",
            "Request",
            "ReportingObserver",
            "ReportBody",
            "ReadableStreamDefaultReader",
            "ReadableStreamDefaultController",
            "ReadableStreamBYOBRequest",
            "ReadableStreamBYOBReader",
            "ReadableStream",
            "ReadableByteStreamController",
            "Range",
            "RadioNodeList",
            "RTCTrackEvent",
            "RTCStatsReport",
            "RTCSessionDescription",
            "RTCSctpTransport",
            "RTCRtpTransceiver",
            "RTCRtpSender",
            "RTCRtpReceiver",
            "RTCPeerConnectionIceEvent",
            "RTCPeerConnectionIceErrorEvent",
            "RTCPeerConnection",
            "RTCIceTransport",
            "RTCIceCandidate",
            "RTCErrorEvent",
            "RTCError",
            "RTCEncodedVideoFrame",
            "RTCEncodedAudioFrame",
            "RTCDtlsTransport",
            "RTCDataChannelEvent",
            "RTCDTMFToneChangeEvent",
            "RTCDTMFSender",
            "RTCCertificate",
            "PromiseRejectionEvent",
            "ProgressEvent",
            "ProcessingInstruction",
            "PopStateEvent",
            "PointerEvent",
            "PluginArray",
            "Plugin",
            "PictureInPictureWindow",
            "PictureInPictureEvent",
            "Permissions",
            "PermissionStatus",
            "PeriodicWave",
            "PerformanceTiming",
            "PerformanceServerTiming",
            "PerformanceScriptTiming",
            "PerformanceResourceTiming",
            "PerformancePaintTiming",
            "PerformanceObserverEntryList",
            "PerformanceObserver",
            "PerformanceNavigationTiming",
            "PerformanceNavigation",
            "PerformanceMeasure",
            "PerformanceMark",
            "PerformanceLongTaskTiming",
            "PerformanceLongAnimationFrameTiming",
            "PerformanceEventTiming",
            "PerformanceEntry",
            "PerformanceElementTiming",
            "Performance",
            "Path2D",
            "PannerNode",
            "PageTransitionEvent",
            "OverconstrainedError",
            "OscillatorNode",
            "OffscreenCanvasRenderingContext2D",
            "OffscreenCanvas",
            "OfflineAudioContext",
            "OfflineAudioCompletionEvent",
            "Observable",
            "NodeList",
            "NodeIterator",
            "NodeFilter",
            "Node",
            "NetworkInformation",
            "NavigatorUAData",
            "Navigator",
            "NavigationTransition",
            "NavigationPrecommitController",
            "NavigationHistoryEntry",
            "NavigationDestination",
            "NavigationCurrentEntryChangeEvent",
            "NavigationActivation",
            "Navigation",
            "NavigateEvent",
            "NamedNodeMap",
            "MutationRecord",
            "MutationObserver",
            "MouseEvent",
            "MimeTypeArray",
            "MimeType",
            "MessagePort",
            "MessageEvent",
            "MessageChannel",
            "MediaStreamTrackVideoStats",
            "MediaStreamTrackProcessor",
            "MediaStreamTrackGenerator",
            "MediaStreamTrackEvent",
            "MediaStreamTrackAudioStats",
            "MediaStreamTrack",
            "MediaStreamEvent",
            "MediaStreamAudioSourceNode",
            "MediaStreamAudioDestinationNode",
            "MediaStream",
            "MediaSourceHandle",
            "MediaSource",
            "MediaRecorder",
            "MediaQueryListEvent",
            "MediaQueryList",
            "MediaList",
            "MediaError",
            "MediaEncryptedEvent",
            "MediaElementAudioSourceNode",
            "MediaCapabilities",
            "MathMLElement",
            "Location",
            "LayoutShiftAttribution",
            "LayoutShift",
            "LargestContentfulPaint",
            "KeyframeEffect",
            "KeyboardEvent",
            "IntersectionObserverEntry",
            "IntersectionObserver",
            "InterestEvent",
            "InputEvent",
            "InputDeviceInfo",
            "InputDeviceCapabilities",
            "Ink",
            "ImageData",
            "ImageBitmapRenderingContext",
            "ImageBitmap",
            "IdleDeadline",
            "IIRFilterNode",
            "IDBVersionChangeEvent",
            "IDBTransaction",
            "IDBRequest",
            "IDBRecord",
            "IDBOpenDBRequest",
            "IDBObjectStore",
            "IDBKeyRange",
            "IDBIndex",
            "IDBFactory",
            "IDBDatabase",
            "IDBCursorWithValue",
            "IDBCursor",
            "History",
            "HighlightRegistry",
            "Highlight",
            "Headers",
            "HashChangeEvent",
            "HTMLVideoElement",
            "HTMLUnknownElement",
            "HTMLUListElement",
            "HTMLTrackElement",
            "HTMLTitleElement",
            "HTMLTimeElement",
            "HTMLTextAreaElement",
            "HTMLTemplateElement",
            "HTMLTableSectionElement",
            "HTMLTableRowElement",
            "HTMLTableElement",
            "HTMLTableColElement",
            "HTMLTableCellElement",
            "HTMLTableCaptionElement",
            "HTMLStyleElement",
            "HTMLSpanElement",
            "HTMLSourceElement",
            "HTMLSlotElement",
            "HTMLSelectedContentElement",
            "HTMLSelectElement",
            "HTMLScriptElement",
            "HTMLQuoteElement",
            "HTMLProgressElement",
            "HTMLPreElement",
            "HTMLPictureElement",
            "HTMLParamElement",
            "HTMLParagraphElement",
            "HTMLOutputElement",
            "HTMLOptionsCollection",
            "HTMLOptionElement",
            "HTMLOptGroupElement",
            "HTMLObjectElement",
            "HTMLOListElement",
            "HTMLModElement",
            "HTMLMeterElement",
            "HTMLMetaElement",
            "HTMLMenuElement",
            "HTMLMediaElement",
            "HTMLMarqueeElement",
            "HTMLMapElement",
            "HTMLLinkElement",
            "HTMLLegendElement",
            "HTMLLabelElement",
            "HTMLLIElement",
            "HTMLInputElement",
            "HTMLImageElement",
            "HTMLIFrameElement",
            "HTMLHtmlElement",
            "HTMLHeadingElement",
            "HTMLHeadElement",
            "HTMLHRElement",
            "HTMLFrameSetElement",
            "HTMLFrameElement",
            "HTMLFormElement",
            "HTMLFormControlsCollection",
            "HTMLFontElement",
            "HTMLFieldSetElement",
            "HTMLEmbedElement",
            "HTMLElement",
            "HTMLDocument",
            "HTMLDivElement",
            "HTMLDirectoryElement",
            "HTMLDialogElement",
            "HTMLDetailsElement",
            "HTMLDataListElement",
            "HTMLDataElement",
            "HTMLDListElement",
            "HTMLCollection",
            "HTMLCanvasElement",
            "HTMLButtonElement",
            "HTMLBodyElement",
            "HTMLBaseElement",
            "HTMLBRElement",
            "HTMLAudioElement",
            "HTMLAreaElement",
            "HTMLAnchorElement",
            "HTMLAllCollection",
            "GeolocationPositionError",
            "GeolocationPosition",
            "GeolocationCoordinates",
            "Geolocation",
            "GamepadHapticActuator",
            "GamepadEvent",
            "GamepadButton",
            "Gamepad",
            "GainNode",
            "FormDataEvent",
            "FormData",
            "FontFaceSetLoadEvent",
            "FontFaceSet",
            "FontFace",
            "FocusEvent",
            "FileReader",
            "FileList",
            "File",
            "FeaturePolicy",
            "External",
            "EventTarget",
            "EventSource",
            "EventCounts",
            "Event",
            "ErrorEvent",
            "EncodedVideoChunk",
            "EncodedAudioChunk",
            "ElementInternals",
            "Element",
            "EditContext",
            "DynamicsCompressorNode",
            "DragEvent",
            "DocumentType",
            "DocumentTimeline",
            "DocumentFragment",
            "Document",
            "DelegatedInkTrailPresenter",
            "DelayNode",
            "DecompressionStream",
            "DataTransferItemList",
            "DataTransferItem",
            "DataTransfer",
            "DOMTokenList",
            "DOMStringMap",
            "DOMStringList",
            "DOMRectReadOnly",
            "DOMRectList",
            "DOMRect",
            "DOMQuad",
            "DOMPointReadOnly",
            "DOMPoint",
            "DOMParser",
            "DOMMatrixReadOnly",
            "DOMMatrix",
            "DOMImplementation",
            "DOMException",
            "DOMError",
            "CustomStateSet",
            "CustomEvent",
            "CustomElementRegistry",
            "Crypto",
            "CountQueuingStrategy",
            "ConvolverNode",
            "ContentVisibilityAutoStateChangeEvent",
            "ConstantSourceNode",
            "CompressionStream",
            "CompositionEvent",
            "Comment",
            "CommandEvent",
            "CloseWatcher",
            "CloseEvent",
            "ClipboardEvent",
            "CharacterData",
            "CharacterBoundsUpdateEvent",
            "ChannelSplitterNode",
            "ChannelMergerNode",
            "CaretPosition",
            "CanvasRenderingContext2D",
            "CanvasPattern",
            "CanvasGradient",
            "CanvasCaptureMediaStreamTrack",
            "CSSViewTransitionRule",
            "CSSVariableReferenceValue",
            "CSSUnparsedValue",
            "CSSUnitValue",
            "CSSTranslate",
            "CSSTransition",
            "CSSTransformValue",
            "CSSTransformComponent",
            "CSSSupportsRule",
            "CSSStyleValue",
            "CSSStyleSheet",
            "CSSStyleRule",
            "CSSStyleDeclaration",
            "CSSStartingStyleRule",
            "CSSSkewY",
            "CSSSkewX",
            "CSSSkew",
            "CSSScopeRule",
            "CSSScale",
            "CSSRuleList",
            "CSSRule",
            "CSSRotate",
            "CSSPropertyRule",
            "CSSPositionValue",
            "CSSPositionTryRule",
            "CSSPositionTryDescriptors",
            "CSSPerspective",
            "CSSPageRule",
            "CSSNumericValue",
            "CSSNumericArray",
            "CSSNestedDeclarations",
            "CSSNamespaceRule",
            "CSSMediaRule",
            "CSSMatrixComponent",
            "CSSMathValue",
            "CSSMathSum",
            "CSSMathProduct",
            "CSSMathNegate",
            "CSSMathMin",
            "CSSMathMax",
            "CSSMathInvert",
            "CSSMathClamp",
            "CSSMarginRule",
            "CSSLayerStatementRule",
            "CSSLayerBlockRule",
            "CSSKeywordValue",
            "CSSKeyframesRule",
            "CSSKeyframeRule",
            "CSSImportRule",
            "CSSImageValue",
            "CSSGroupingRule",
            "CSSFontPaletteValuesRule",
            "CSSFontFaceRule",
            "CSSCounterStyleRule",
            "CSSContainerRule",
            "CSSConditionRule",
            "CSSAnimation",
            "CSS",
            "CSPViolationReportBody",
            "CDATASection",
            "ByteLengthQueuingStrategy",
            "BrowserCaptureMediaStreamTrack",
            "BroadcastChannel",
            "BlobEvent",
            "Blob",
            "BiquadFilterNode",
            "BeforeUnloadEvent",
            "BeforeInstallPromptEvent",
            "BaseAudioContext",
            "BarProp",
            "AudioWorkletNode",
            "AudioSinkInfo",
            "AudioScheduledSourceNode",
            "AudioProcessingEvent",
            "AudioParamMap",
            "AudioParam",
            "AudioNode",
            "AudioListener",
            "AudioDestinationNode",
            "AudioData",
            "AudioContext",
            "AudioBufferSourceNode",
            "AudioBuffer",
            "Attr",
            "AnimationTimeline",
            "AnimationPlaybackEvent",
            "AnimationEvent",
            "AnimationEffect",
            "Animation",
            "AnalyserNode",
            "AbstractRange",
            "AbortSignal",
            "AbortController",
            "window",
            "self",
            "document",
            "name",
            "location",
            "customElements",
            "history",
            "navigation",
            "locationbar",
            "menubar",
            "personalbar",
            "scrollbars",
            "statusbar",
            "toolbar",
            "status",
            "closed",
            "frames",
            "length",
            "top",
            "opener",
            "parent",
            "frameElement",
            "navigator",
            "origin",
            "external",
            "screen",
            "innerWidth",
            "innerHeight",
            "scrollX",
            "pageXOffset",
            "scrollY",
            "pageYOffset",
            "visualViewport",
            "screenX",
            "screenY",
            "outerWidth",
            "outerHeight",
            "devicePixelRatio",
            "event",
            "clientInformation",
            "offscreenBuffering",
            "screenLeft",
            "screenTop",
            "styleMedia",
            "onsearch",
            "onappinstalled",
            "onbeforeinstallprompt",
            "onabort",
            "onbeforeinput",
            "onbeforematch",
            "onbeforetoggle",
            "onblur",
            "oncancel",
            "oncanplay",
            "oncanplaythrough",
            "onchange",
            "onclick",
            "onclose",
            "oncommand",
            "oncontentvisibilityautostatechange",
            "oncontextlost",
            "oncontextmenu",
            "oncontextrestored",
            "oncuechange",
            "ondblclick",
            "ondrag",
            "ondragend",
            "ondragenter",
            "ondragleave",
            "ondragover",
            "ondragstart",
            "ondrop",
            "ondurationchange",
            "onemptied",
            "onended",
            "onerror",
            "onfocus",
            "onformdata",
            "oninput",
            "oninvalid",
            "onkeydown",
            "onkeypress",
            "onkeyup",
            "onload",
            "onloadeddata",
            "onloadedmetadata",
            "onloadstart",
            "onmousedown",
            "onmouseenter",
            "onmouseleave",
            "onmousemove",
            "onmouseout",
            "onmouseover",
            "onmouseup",
            "onmousewheel",
            "onpause",
            "onplay",
            "onplaying",
            "onprogress",
            "onratechange",
            "onreset",
            "onresize",
            "onscroll",
            "onscrollend",
            "onsecuritypolicyviolation",
            "onseeked",
            "onseeking",
            "onselect",
            "onslotchange",
            "onstalled",
            "onsubmit",
            "onsuspend",
            "ontimeupdate",
            "ontoggle",
            "onvolumechange",
            "onwaiting",
            "onwebkitanimationend",
            "onwebkitanimationiteration",
            "onwebkitanimationstart",
            "onwebkittransitionend",
            "onwheel",
            "onauxclick",
            "ongotpointercapture",
            "onlostpointercapture",
            "onpointerdown",
            "onpointermove",
            "onpointerup",
            "onpointercancel",
            "onpointerover",
            "onpointerout",
            "onpointerenter",
            "onpointerleave",
            "onselectstart",
            "onselectionchange",
            "onanimationcancel",
            "onanimationend",
            "onanimationiteration",
            "onanimationstart",
            "ontransitionrun",
            "ontransitionstart",
            "ontransitionend",
            "ontransitioncancel",
            "onbeforexrselect",
            "onafterprint",
            "onbeforeprint",
            "onbeforeunload",
            "onhashchange",
            "onlanguagechange",
            "onmessage",
            "onmessageerror",
            "onoffline",
            "ononline",
            "onpagehide",
            "onpageshow",
            "onpopstate",
            "onrejectionhandled",
            "onstorage",
            "onunhandledrejection",
            "onunload",
            "isSecureContext",
            "crossOriginIsolated",
            "scheduler",
            "performance",
            "trustedTypes",
            "crypto",
            "indexedDB",
            "localStorage",
            "sessionStorage",
            "alert",
            "atob",
            "blur",
            "btoa",
            "cancelAnimationFrame",
            "cancelIdleCallback",
            "captureEvents",
            "clearInterval",
            "clearTimeout",
            "close",
            "confirm",
            "createImageBitmap",
            "fetch",
            "find",
            "focus",
            "getComputedStyle",
            "getSelection",
            "matchMedia",
            "moveBy",
            "moveTo",
            "open",
            "postMessage",
            "print",
            "prompt",
            "queueMicrotask",
            "releaseEvents",
            "reportError",
            "requestAnimationFrame",
            "requestIdleCallback",
            "resizeBy",
            "resizeTo",
            "scroll",
            "scrollBy",
            "scrollTo",
            "setInterval",
            "setTimeout",
            "stop",
            "structuredClone",
            "webkitCancelAnimationFrame",
            "webkitRequestAnimationFrame",
            "Temporal",
            "SuppressedError",
            "DisposableStack",
            "AsyncDisposableStack",
            "Float16Array",
            "chrome",
            "WebAssembly",
            "crashReport",
            "cookieStore",
            "ondevicemotion",
            "ondeviceorientation",
            "ondeviceorientationabsolute",
            "onpointerrawupdate",
            "caches",
            "documentPictureInPicture",
            "sharedStorage",
            "AbsoluteOrientationSensor",
            "Accelerometer",
            "AudioDecoder",
            "AudioEncoder",
            "AudioWorklet",
            "BatteryManager",
            "Cache",
            "CacheStorage",
            "Clipboard",
            "ClipboardChangeEvent",
            "ClipboardItem",
            "CookieChangeEvent",
            "CookieStore",
            "CookieStoreManager",
            "CreateMonitor",
            "Credential",
            "CredentialsContainer",
            "CryptoKey",
            "DeviceMotionEvent",
            "DeviceMotionEventAcceleration",
            "DeviceMotionEventRotationRate",
            "DeviceOrientationEvent",
            "FederatedCredential",
            "GPU",
            "GPUAdapter",
            "GPUAdapterInfo",
            "GPUBindGroup",
            "GPUBindGroupLayout",
            "GPUBuffer",
            "GPUBufferUsage",
            "GPUCanvasContext",
            "GPUColorWrite",
            "GPUCommandBuffer",
            "GPUCommandEncoder",
            "GPUCompilationInfo",
            "GPUCompilationMessage",
            "GPUComputePassEncoder",
            "GPUComputePipeline",
            "GPUDevice",
            "GPUDeviceLostInfo",
            "GPUError",
            "GPUExternalTexture",
            "GPUInternalError",
            "GPUMapMode",
            "GPUOutOfMemoryError",
            "GPUPipelineError",
            "GPUPipelineLayout",
            "GPUQuerySet",
            "GPUQueue",
            "GPURenderBundle",
            "GPURenderBundleEncoder",
            "GPURenderPassEncoder",
            "GPURenderPipeline",
            "GPUSampler",
            "GPUShaderModule",
            "GPUShaderStage",
            "GPUSupportedFeatures",
            "GPUSupportedLimits",
            "GPUTexture",
            "GPUTextureUsage",
            "GPUTextureView",
            "GPUUncapturedErrorEvent",
            "GPUValidationError",
            "GravitySensor",
            "Gyroscope",
            "IdleDetector",
            "ImageCapture",
            "ImageDecoder",
            "ImageTrack",
            "ImageTrackList",
            "Keyboard",
            "KeyboardLayoutMap",
            "LinearAccelerationSensor",
            "MIDIAccess",
            "MIDIConnectionEvent",
            "MIDIInput",
            "MIDIInputMap",
            "MIDIMessageEvent",
            "MIDIOutput",
            "MIDIOutputMap",
            "MIDIPort",
            "MediaDeviceInfo",
            "MediaDevices",
            "MediaKeyMessageEvent",
            "MediaKeySession",
            "MediaKeyStatusMap",
            "MediaKeySystemAccess",
            "MediaKeys",
            "NavigationPreloadManager",
            "NavigatorManagedData",
            "OrientationSensor",
            "PasswordCredential",
            "ProtectedAudience",
            "RelativeOrientationSensor",
            "ScreenDetailed",
            "ScreenDetails",
            "Sensor",
            "SensorErrorEvent",
            "ServiceWorkerRegistration",
            "StorageManager",
            "SubtleCrypto",
            "VideoDecoder",
            "VideoEncoder",
            "VirtualKeyboard",
            "WGSLLanguageFeatures",
            "WebTransport",
            "WebTransportBidirectionalStream",
            "WebTransportDatagramDuplexStream",
            "WebTransportError",
            "Worklet",
            "XRDOMOverlayState",
            "XRLayer",
            "XRWebGLBinding",
            "AudioPlaybackStats",
            "AuthenticatorAssertionResponse",
            "AuthenticatorAttestationResponse",
            "AuthenticatorResponse",
            "PublicKeyCredential",
            "Bluetooth",
            "BluetoothCharacteristicProperties",
            "BluetoothDevice",
            "BluetoothRemoteGATTCharacteristic",
            "BluetoothRemoteGATTDescriptor",
            "BluetoothRemoteGATTServer",
            "BluetoothRemoteGATTService",
            "CaptureController",
            "CrashReportContext",
            "DevicePosture",
            "DigitalCredential",
            "DocumentPictureInPicture",
            "EyeDropper",
            "FetchLaterResult",
            "FileSystemDirectoryHandle",
            "FileSystemFileHandle",
            "FileSystemHandle",
            "FileSystemWritableFileStream",
            "FileSystemObserver",
            "FontData",
            "FragmentDirective",
            "HID",
            "HIDConnectionEvent",
            "HIDDevice",
            "HIDInputReportEvent",
            "IdentityCredential",
            "IdentityCredentialError",
            "IdentityProvider",
            "NavigatorLogin",
            "LanguageDetector",
            "Lock",
            "LockManager",
            "ServiceWorker",
            "ServiceWorkerContainer",
            "NotRestoredReasonDetails",
            "NotRestoredReasons",
            "OTPCredential",
            "PaymentAddress",
            "PaymentRequest",
            "PaymentRequestUpdateEvent",
            "PaymentResponse",
            "PaymentManager",
            "PaymentMethodChangeEvent",
            "Presentation",
            "PresentationAvailability",
            "PresentationConnection",
            "PresentationConnectionAvailableEvent",
            "PresentationConnectionCloseEvent",
            "PresentationConnectionList",
            "PresentationReceiver",
            "PresentationRequest",
            "PressureObserver",
            "PressureRecord",
            "Serial",
            "SerialPort",
            "SpeechRecognitionPhrase",
            "StorageBucket",
            "StorageBucketManager",
            "Summarizer",
            "Translator",
            "USB",
            "USBAlternateInterface",
            "USBConfiguration",
            "USBConnectionEvent",
            "USBDevice",
            "USBEndpoint",
            "USBInTransferResult",
            "USBInterface",
            "USBIsochronousInTransferPacket",
            "USBIsochronousInTransferResult",
            "USBIsochronousOutTransferPacket",
            "USBIsochronousOutTransferResult",
            "USBOutTransferResult",
            "WakeLock",
            "WakeLockSentinel",
            "XRAnchor",
            "XRAnchorSet",
            "XRBoundedReferenceSpace",
            "XRCPUDepthInformation",
            "XRCamera",
            "XRDepthInformation",
            "XRFrame",
            "XRHand",
            "XRHitTestResult",
            "XRHitTestSource",
            "XRInputSource",
            "XRInputSourceArray",
            "XRInputSourceEvent",
            "XRInputSourcesChangeEvent",
            "XRJointPose",
            "XRJointSpace",
            "XRLightEstimate",
            "XRLightProbe",
            "XRPose",
            "XRRay",
            "XRReferenceSpace",
            "XRReferenceSpaceEvent",
            "XRRenderState",
            "XRRigidTransform",
            "XRSession",
            "XRSessionEvent",
            "XRSpace",
            "XRSystem",
            "XRTransientInputHitTestResult",
            "XRTransientInputHitTestSource",
            "XRView",
            "XRViewerPose",
            "XRViewport",
            "XRWebGLDepthInformation",
            "XRWebGLLayer",
            "XRCompositionLayer",
            "XRProjectionLayer",
            "XRCubeLayer",
            "XRCylinderLayer",
            "XREquirectLayer",
            "XRLayerEvent",
            "XRQuadLayer",
            "XRSubImage",
            "XRWebGLSubImage",
            "XRPlane",
            "XRPlaneSet",
            "XRVisibilityMaskChangeEvent",
            "fetchLater",
            "getDigitalGoodsService",
            "getScreenDetails",
            "queryLocalFonts",
            "showDirectoryPicker",
            "showOpenFilePicker",
            "showSaveFilePicker",
            "originAgentCluster",
            "viewport",
            "onpageswap",
            "onpagereveal",
            "credentialless",
            "fence",
            "launchQueue",
            "speechSynthesis",
            "onscrollsnapchange",
            "onscrollsnapchanging",
            "ongamepadconnected",
            "ongamepaddisconnected",
            "AnimationTrigger",
            "BackgroundFetchManager",
            "BackgroundFetchRecord",
            "BackgroundFetchRegistration",
            "BluetoothUUID",
            "CSSFontFeatureValuesRule",
            "CSSFunctionDeclarations",
            "CSSFunctionDescriptors",
            "CSSFunctionRule",
            "CSSPseudoElement",
            "ChapterInformation",
            "CropTarget",
            "DocumentPictureInPictureEvent",
            "Fence",
            "FencedFrameConfig",
            "HTMLFencedFrameElement",
            "HTMLGeolocationElement",
            "HTMLUserMediaElement",
            "IntegrityViolationReportBody",
            "InteractionContentfulPaint",
            "PerformanceSoftNavigation",
            "LaunchParams",
            "LaunchQueue",
            "MediaMetadata",
            "MediaSession",
            "Notification",
            "Origin",
            "PageRevealEvent",
            "PageSwapEvent",
            "PerformanceTimingConfidence",
            "PeriodicSyncManager",
            "Profiler",
            "PushManager",
            "PushSubscription",
            "PushSubscriptionOptions",
            "QuotaExceededError",
            "RTCDataChannel",
            "RTCRtpScriptTransform",
            "RemotePlayback",
            "RestrictionTarget",
            "Sanitizer",
            "SharedStorage",
            "SharedStorageWorklet",
            "SharedStorageAppendMethod",
            "SharedStorageClearMethod",
            "SharedStorageDeleteMethod",
            "SharedStorageModifierMethod",
            "SharedStorageSetMethod",
            "SharedWorker",
            "SnapEvent",
            "SpeechGrammar",
            "SpeechGrammarList",
            "SpeechRecognition",
            "SpeechRecognitionErrorEvent",
            "SpeechRecognitionEvent",
            "SpeechSynthesis",
            "SpeechSynthesisErrorEvent",
            "SpeechSynthesisEvent",
            "SpeechSynthesisUtterance",
            "SpeechSynthesisVoice",
            "TimelineTrigger",
            "TimelineTriggerRange",
            "TimelineTriggerRangeList",
            "Viewport",
            "WebSocketError",
            "WebSocketStream",
            "XSLTProcessor",
            "webkitSpeechGrammar",
            "webkitSpeechGrammarList",
            "webkitSpeechRecognition",
            "webkitSpeechRecognitionError",
            "webkitSpeechRecognitionEvent",
            "webkitRequestFileSystem",
            "webkitResolveLocalFileSystemURL",
            "sa_event_loaded",
            "sa_loaded",
            "sa_event",
            "applyFocusVisiblePolyfill",
            "captchaFoxOnLoad",
            "__core-js_shared__",
            "__svelte",
            "captchafox",
            "_0x5e41",
            "__cf_wapi",
            "_0x30fc",
            "TEMPORARY",
            "PERSISTENT",
            "constructor",
            "addEventListener",
            "dispatchEvent",
            "removeEventListener",
            "when",
            "constructor"
        ],
        "CF0131": [
            "location",
            "_reactListeningn0a0q77o4ho",
            "constructor",
            "implementation",
            "URL",
            "documentURI",
            "compatMode",
            "characterSet",
            "charset",
            "inputEncoding",
            "contentType",
            "doctype",
            "documentElement",
            "xmlEncoding",
            "xmlVersion",
            "xmlStandalone",
            "domain",
            "referrer",
            "cookie",
            "lastModified",
            "readyState",
            "title",
            "dir",
            "body",
            "head",
            "images",
            "embeds",
            "plugins",
            "links",
            "forms",
            "scripts",
            "currentScript",
            "defaultView",
            "designMode",
            "onreadystatechange",
            "anchors",
            "applets",
            "fgColor",
            "linkColor",
            "vlinkColor",
            "alinkColor",
            "bgColor",
            "all",
            "scrollingElement",
            "onpointerlockchange",
            "onpointerlockerror",
            "hidden",
            "visibilityState",
            "wasDiscarded",
            "prerendering",
            "featurePolicy",
            "webkitVisibilityState",
            "webkitHidden",
            "onbeforecopy",
            "onbeforecut",
            "onbeforepaste",
            "onfreeze",
            "onprerenderingchange",
            "onresume",
            "onsearch",
            "onvisibilitychange",
            "timeline",
            "fullscreenEnabled",
            "fullscreen",
            "onfullscreenchange",
            "onfullscreenerror",
            "webkitIsFullScreen",
            "webkitCurrentFullScreenElement",
            "webkitFullscreenEnabled",
            "webkitFullscreenElement",
            "onwebkitfullscreenchange",
            "onwebkitfullscreenerror",
            "rootElement",
            "pictureInPictureEnabled",
            "onabort",
            "onbeforeinput",
            "onbeforematch",
            "onbeforetoggle",
            "onblur",
            "oncancel",
            "oncanplay",
            "oncanplaythrough",
            "onchange",
            "onclick",
            "onclose",
            "oncommand",
            "oncontentvisibilityautostatechange",
            "oncontextlost",
            "oncontextmenu",
            "oncontextrestored",
            "oncuechange",
            "ondblclick",
            "ondrag",
            "ondragend",
            "ondragenter",
            "ondragleave",
            "ondragover",
            "ondragstart",
            "ondrop",
            "ondurationchange",
            "onemptied",
            "onended",
            "onerror",
            "onfocus",
            "onformdata",
            "oninput",
            "oninvalid",
            "onkeydown",
            "onkeypress",
            "onkeyup",
            "onload",
            "onloadeddata",
            "onloadedmetadata",
            "onloadstart",
            "onmousedown",
            "onmouseenter",
            "onmouseleave",
            "onmousemove",
            "onmouseout",
            "onmouseover",
            "onmouseup",
            "onmousewheel",
            "onpause",
            "onplay",
            "onplaying",
            "onprogress",
            "onratechange",
            "onreset",
            "onresize",
            "onscroll",
            "onscrollend",
            "onsecuritypolicyviolation",
            "onseeked",
            "onseeking",
            "onselect",
            "onslotchange",
            "onstalled",
            "onsubmit",
            "onsuspend",
            "ontimeupdate",
            "ontoggle",
            "onvolumechange",
            "onwaiting",
            "onwebkitanimationend",
            "onwebkitanimationiteration",
            "onwebkitanimationstart",
            "onwebkittransitionend",
            "onwheel",
            "onauxclick",
            "ongotpointercapture",
            "onlostpointercapture",
            "onpointerdown",
            "onpointermove",
            "onpointerup",
            "onpointercancel",
            "onpointerover",
            "onpointerout",
            "onpointerenter",
            "onpointerleave",
            "onselectstart",
            "onselectionchange",
            "onanimationcancel",
            "onanimationend",
            "onanimationiteration",
            "onanimationstart",
            "ontransitionrun",
            "ontransitionstart",
            "ontransitionend",
            "ontransitioncancel",
            "onbeforexrselect",
            "oncopy",
            "oncut",
            "onpaste",
            "children",
            "firstElementChild",
            "lastElementChild",
            "childElementCount",
            "activeElement",
            "styleSheets",
            "pointerLockElement",
            "fullscreenElement",
            "adoptedStyleSheets",
            "pictureInPictureElement",
            "fonts",
            "adoptNode",
            "append",
            "captureEvents",
            "caretPositionFromPoint",
            "caretRangeFromPoint",
            "clear",
            "close",
            "createAttribute",
            "createAttributeNS",
            "createCDATASection",
            "createComment",
            "createDocumentFragment",
            "createElement",
            "createElementNS",
            "createEvent",
            "createExpression",
            "createNSResolver",
            "createNodeIterator",
            "createProcessingInstruction",
            "createRange",
            "createTextNode",
            "createTreeWalker",
            "elementFromPoint",
            "elementsFromPoint",
            "evaluate",
            "execCommand",
            "exitFullscreen",
            "exitPictureInPicture",
            "exitPointerLock",
            "getAnimations",
            "getElementById",
            "getElementsByClassName",
            "getElementsByName",
            "getElementsByTagName",
            "getElementsByTagNameNS",
            "getSelection",
            "hasFocus",
            "hasStorageAccess",
            "hasUnpartitionedCookieAccess",
            "importNode",
            "moveBefore",
            "open",
            "prepend",
            "queryCommandEnabled",
            "queryCommandIndeterm",
            "queryCommandState",
            "queryCommandSupported",
            "queryCommandValue",
            "querySelector",
            "querySelectorAll",
            "releaseEvents",
            "replaceChildren",
            "requestStorageAccess",
            "requestStorageAccessFor",
            "startViewTransition",
            "webkitCancelFullScreen",
            "webkitExitFullscreen",
            "write",
            "writeln",
            "constructor",
            "fragmentDirective",
            "onpointerrawupdate",
            "browsingTopics",
            "hasPrivateToken",
            "hasRedemptionRecord",
            "activeViewTransition",
            "onscrollsnapchange",
            "onscrollsnapchanging",
            "customElementRegistry",
            "ariaNotify",
            "nodeType",
            "nodeName",
            "baseURI",
            "isConnected",
            "ownerDocument",
            "parentNode",
            "parentElement",
            "childNodes",
            "firstChild",
            "lastChild",
            "previousSibling",
            "nextSibling",
            "nodeValue",
            "textContent",
            "ELEMENT_NODE",
            "ATTRIBUTE_NODE",
            "TEXT_NODE",
            "CDATA_SECTION_NODE",
            "ENTITY_REFERENCE_NODE",
            "ENTITY_NODE",
            "PROCESSING_INSTRUCTION_NODE",
            "COMMENT_NODE",
            "DOCUMENT_NODE",
            "DOCUMENT_TYPE_NODE",
            "DOCUMENT_FRAGMENT_NODE",
            "NOTATION_NODE",
            "DOCUMENT_POSITION_DISCONNECTED",
            "DOCUMENT_POSITION_PRECEDING",
            "DOCUMENT_POSITION_FOLLOWING",
            "DOCUMENT_POSITION_CONTAINS",
            "DOCUMENT_POSITION_CONTAINED_BY",
            "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
            "appendChild",
            "cloneNode",
            "compareDocumentPosition",
            "contains",
            "getRootNode",
            "hasChildNodes",
            "insertBefore",
            "isDefaultNamespace",
            "isEqualNode",
            "isSameNode",
            "lookupNamespaceURI",
            "lookupPrefix",
            "normalize",
            "removeChild",
            "replaceChild",
            "constructor",
            "addEventListener",
            "dispatchEvent",
            "removeEventListener",
            "when",
            "constructor"
        ],
        "CF0132": [
            "vendorSub",
            "productSub",
            "vendor",
            "maxTouchPoints",
            "scheduling",
            "userActivation",
            "geolocation",
            "doNotTrack",
            "webkitTemporaryStorage",
            "webkitPersistentStorage",
            "windowControlsOverlay",
            "hardwareConcurrency",
            "cookieEnabled",
            "appCodeName",
            "appName",
            "appVersion",
            "platform",
            "product",
            "userAgent",
            "language",
            "languages",
            "onLine",
            "webdriver",
            "plugins",
            "mimeTypes",
            "pdfViewerEnabled",
            "connection",
            "getGamepads",
            "javaEnabled",
            "sendBeacon",
            "vibrate",
            "constructor",
            "deprecatedRunAdAuctionEnforcesKAnonymity",
            "protectedAudience",
            "bluetooth",
            "clipboard",
            "credentials",
            "keyboard",
            "managed",
            "mediaDevices",
            "serviceWorker",
            "virtualKeyboard",
            "wakeLock",
            "deviceMemory",
            "userAgentData",
            "locks",
            "storage",
            "gpu",
            "login",
            "ink",
            "mediaCapabilities",
            "permissions",
            "devicePosture",
            "hid",
            "mediaSession",
            "presentation",
            "serial",
            "usb",
            "xr",
            "storageBuckets",
            "adAuctionComponents",
            "runAdAuction",
            "canLoadAdAuctionFencedFrame",
            "canShare",
            "share",
            "clearAppBadge",
            "getBattery",
            "getUserMedia",
            "requestMIDIAccess",
            "requestMediaKeySystemAccess",
            "setAppBadge",
            "webkitGetUserMedia",
            "clearOriginJoinedAdInterestGroups",
            "createAuctionNonce",
            "joinAdInterestGroup",
            "leaveAdInterestGroup",
            "updateAdInterestGroups",
            "deprecatedReplaceInURN",
            "deprecatedURNToURL",
            "getInstalledRelatedApps",
            "getInterestGroupAdAuctionData",
            "registerProtocolHandler",
            "unregisterProtocolHandler"
        ],
        "CF0133": [
            "lang",
            "class",
            "data-js-focus-visible"
        ],
        "CF0134": "object",
        "CF0135": false,
        "CF0136": 33,
        "CF0137": false,
        "CF0138": false,
        "CF0139": false,
        "CF0140": false,
        "CF0141": false,
        "CF0142": true,
        "CF0143": true,
        "CF0144": [
            true,
            true
        ],
        "CF0145": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0",
        "CF0146": false,
        "CF0147": false,
        "CF0148": "https://portal.captchafox.com/register"
    },
    "host": "portal.captchafox.com",
    "k": 12583,
    "type": "slide"
}
console.log(typedArrayToBase64(gu(config_fp)));
