# import requests
from curl_cffi import requests
from loguru import logger
from payload_crypt import CapFoxCrypt
import hashlib
import random
from typing import List

class CaptchaFox:
    def __init__(self, site_key, site):
        self.site_key = site_key or "sk_WTsTCEH6Kswd_Y5Lmhe2eMARiBTJoScs"
        self.site = site or "https://portal.captchafox.com/register"
        self.origin = ""
        self.referer = ""
        self.user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0"
        self.pulse = "b91270d05dc447c5"
        self.lng = "zh-cn"
        # 出现网络问题可自行配置代理
        # self.proxy = {
        #     'http': 'http://127.0.0.1:7897',
        #     'https': 'http://127.0.0.1:7897',
        # }
        self.proxy = None
        self.h = ""
        self.m = []
        self.k = 0

    @staticmethod
    def proof_of_work(params: list) -> int:
        """
        找到使 SHA-256 哈希前导零数量达标的 nonce
        """
        if len(params) != 3:
            raise ValueError("bad input")

        base_string = params[1]
        required_zeros = int(params[2], 2)
        nonce = 0

        while True:
            hash_hex = hashlib.sha256(f"{base_string}{nonce}".encode()).hexdigest()
            if hash_hex[:required_zeros] == "0" * required_zeros:
                return nonce
            nonce += 1

    def get_config(self):

        headers = {
            "accept": "*/*",
            "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
            "cache-control": "no-cache",
            "origin": "https://portal.captchafox.com",
            "pragma": "no-cache",
            "priority": "u=1, i",
            "referer": "https://portal.captchafox.com/",
            "sec-ch-ua": "\"Not=A?Brand\";v=\"99\", \"Microsoft Edge\";v=\"151\", \"Chromium\";v=\"151\"",
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "\"Windows\"",
            "sec-fetch-dest": "empty",
            "sec-fetch-mode": "cors",
            "sec-fetch-site": "same-site",
            "user-agent": self.user_agent,
            "x-pulse": self.pulse
        }

        params = {
            "site": self.site
        }

        try:

            response = requests.get(
                f"https://api.captchafox.com/captcha/{self.site_key}/config",
                headers=headers,
                params=params,
                proxies=self.proxy
            )
            resp_json = response.json()
            self.h = resp_json.get("h","")
            self.m = resp_json.get("m","")

            logger.debug(f"[get_config running] resp_json: {resp_json}")
            logger.debug(f"[get_config running] h: {self.h}")
            logger.debug(f"[get_config running] m: {self.m}")

        except Exception as e:
            logger.error(f"[get_config except] error info: {e}")

    def solver_challenge(self):

        if not self.h:
            logger.warning("[CaptchaFox.solver_challenge running] h is None")
        if not self.m:
            logger.warning("[CaptchaFox.solver_challenge running] m is None")

        self.k = CaptchaFox.proof_of_work(self.m)

        fp_json = {'lng': self.lng,
                   'h': self.h,
                   'cs': {'CF0100': False, 'CF0101': True,
                          'CF0102': {'depth': 3548, 'msg': 'Maximum call stack size exceeded', 'name': 'RangeError',
                                     'length': 954}, 'CF0103': True, 'CF0104': False, 'CF0105': 32,
                          'CF0106': 1787983409399, 'CF0107': False, 'CF0108': -480, 'CF0109': False,
                          'CF0110': {'state': 'prompt', 'permission': 'default'},
                          'CF0111': ['zh-CN', 'en', 'en-GB', 'en-US'], 'CF0112': False, 'CF0113': False,
                          'CF0114': ['Google Inc. (Microsoft)',
                                     'ANGLE (Microsoft, Microsoft Basic Render Driver (0x0000008C) Direct3D11 vs_5_0 ps_5_0, D3D11)',
                                     'WebKit', 'WebKit WebGL', 'WebGL 1.0 (OpenGL ES 2.0 Chromium)'],
                          'CF0115': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0',
                          'CF0116': {'brands': [{'brand': 'Not=A?Brand', 'version': '99'},
                                                {'brand': 'Microsoft Edge', 'version': '151'},
                                                {'brand': 'Chromium', 'version': '151'}], 'mobile': False,
                                     'platform': 'Windows'}, 'CF0117': 'Google Inc.', 'CF0118': 'Win32',
                          'CF0119': '20030107',
                          'CF0120': {'width': 1536, 'height': 864, 'availW': 1536, 'availH': 824, 'clrDepth': 24,
                                     'pxDepth': 24, 'pxRatio': 1.25, 'outerW': 1536, 'outerH': 824},
                          'CF0121': ['Google Inc. (Microsoft)',
                                     'ANGLE (Microsoft, Microsoft Basic Render Driver (0x0000008C) Direct3D11 vs_5_0 ps_5_0, D3D11)'],
                          'CF0122': {'ogg': '', 'h264': 'probably', 'webm': 'probably'}, 'CF0123': True,
                          'CF0124': ['PDF Viewer:Portable Document Format:internal-pdf-viewer',
                                     'Chrome PDF Viewer:Portable Document Format:internal-pdf-viewer',
                                     'Chromium PDF Viewer:Portable Document Format:internal-pdf-viewer',
                                     'Microsoft Edge PDF Viewer:Portable Document Format:internal-pdf-viewer',
                                     'WebKit built-in PDF:Portable Document Format:internal-pdf-viewer'],
                          'CF0125': True, 'CF0126': ['Portable Document Format~application/pdf~pdf',
                                                     'Portable Document Format~text/pdf~pdf'], 'CF0127': True,
                          'CF0128': 'function close() { [native code] }', 'CF0129': '[object External]',
                          'CF0130': ['Object', 'Function', 'Array', 'Number', 'parseFloat', 'parseInt', 'Infinity',
                                     'NaN', 'undefined', 'Boolean', 'String', 'Symbol', 'Date', 'Promise', 'RegExp',
                                     'Error', 'AggregateError', 'EvalError', 'RangeError', 'ReferenceError',
                                     'SyntaxError', 'TypeError', 'URIError', 'globalThis', 'JSON', 'Math', 'Intl',
                                     'ArrayBuffer', 'Atomics', 'Uint8Array', 'Int8Array', 'Uint16Array', 'Int16Array',
                                     'Uint32Array', 'Int32Array', 'BigUint64Array', 'BigInt64Array',
                                     'Uint8ClampedArray', 'Float32Array', 'Float64Array', 'DataView', 'Map', 'BigInt',
                                     'Set', 'Iterator', 'WeakMap', 'WeakSet', 'Proxy', 'Reflect',
                                     'FinalizationRegistry', 'WeakRef', 'decodeURI', 'decodeURIComponent', 'encodeURI',
                                     'encodeURIComponent', 'escape', 'unescape', 'eval', 'isFinite', 'isNaN', 'console',
                                     'Option', 'Image', 'Audio', 'webkitURL', 'webkitRTCPeerConnection',
                                     'webkitMediaStream', 'WebKitMutationObserver', 'WebKitCSSMatrix', 'XPathResult',
                                     'XPathExpression', 'XPathEvaluator', 'XMLSerializer', 'XMLHttpRequestUpload',
                                     'XMLHttpRequestEventTarget', 'XMLHttpRequest', 'XMLDocument',
                                     'WritableStreamDefaultWriter', 'WritableStreamDefaultController', 'WritableStream',
                                     'Worker', 'WindowControlsOverlayGeometryChangeEvent', 'WindowControlsOverlay',
                                     'Window', 'WheelEvent', 'WebSocket', 'WebGLVertexArrayObject',
                                     'WebGLUniformLocation', 'WebGLTransformFeedback', 'WebGLTexture', 'WebGLSync',
                                     'WebGLShaderPrecisionFormat', 'WebGLShader', 'WebGLSampler',
                                     'WebGLRenderingContext', 'WebGLRenderbuffer', 'WebGLQuery', 'WebGLProgram',
                                     'WebGLObject', 'WebGLFramebuffer', 'WebGLContextEvent', 'WebGLBuffer',
                                     'WebGLActiveInfo', 'WebGL2RenderingContext', 'WaveShaperNode', 'VisualViewport',
                                     'VisibilityStateEntry', 'VirtualKeyboardGeometryChangeEvent',
                                     'ViewTransitionTypeSet', 'ViewTransition', 'ViewTimeline', 'VideoPlaybackQuality',
                                     'VideoFrame', 'VideoColorSpace', 'ValidityState', 'VTTCue', 'UserActivation',
                                     'URLSearchParams', 'URLPattern', 'URL', 'UIEvent', 'TrustedTypePolicyFactory',
                                     'TrustedTypePolicy', 'TrustedScriptURL', 'TrustedScript', 'TrustedHTML',
                                     'TreeWalker', 'TransitionEvent', 'TransformStreamDefaultController',
                                     'TransformStream', 'TrackEvent', 'TouchList', 'TouchEvent', 'Touch', 'ToggleEvent',
                                     'TimeRanges', 'TextUpdateEvent', 'TextTrackList', 'TextTrackCueList',
                                     'TextTrackCue', 'TextTrack', 'TextMetrics', 'TextFormatUpdateEvent', 'TextFormat',
                                     'TextEvent', 'TextEncoderStream', 'TextEncoder', 'TextDecoderStream',
                                     'TextDecoder', 'Text', 'TaskSignal', 'TaskPriorityChangeEvent', 'TaskController',
                                     'TaskAttributionTiming', 'SyncManager', 'Subscriber', 'SubmitEvent',
                                     'StyleSheetList', 'StyleSheet', 'StylePropertyMapReadOnly', 'StylePropertyMap',
                                     'StorageEvent', 'Storage', 'StereoPannerNode', 'StaticRange', 'SourceBufferList',
                                     'SourceBuffer', 'ShadowRoot', 'Selection', 'SecurityPolicyViolationEvent',
                                     'ScrollTimeline', 'ScriptProcessorNode', 'ScreenOrientation', 'Screen',
                                     'Scheduling', 'Scheduler', 'SVGViewElement', 'SVGUseElement', 'SVGUnitTypes',
                                     'SVGTransformList', 'SVGTransform', 'SVGTitleElement', 'SVGTextPositioningElement',
                                     'SVGTextPathElement', 'SVGTextElement', 'SVGTextContentElement', 'SVGTSpanElement',
                                     'SVGSymbolElement', 'SVGSwitchElement', 'SVGStyleElement', 'SVGStringList',
                                     'SVGStopElement', 'SVGSetElement', 'SVGScriptElement', 'SVGSVGElement',
                                     'SVGRectElement', 'SVGRect', 'SVGRadialGradientElement', 'SVGPreserveAspectRatio',
                                     'SVGPolylineElement', 'SVGPolygonElement', 'SVGPointList', 'SVGPoint',
                                     'SVGPatternElement', 'SVGPathElement', 'SVGNumberList', 'SVGNumber',
                                     'SVGMetadataElement', 'SVGMatrix', 'SVGMaskElement', 'SVGMarkerElement',
                                     'SVGMPathElement', 'SVGLinearGradientElement', 'SVGLineElement', 'SVGLengthList',
                                     'SVGLength', 'SVGImageElement', 'SVGGraphicsElement', 'SVGGradientElement',
                                     'SVGGeometryElement', 'SVGGElement', 'SVGForeignObjectElement', 'SVGFilterElement',
                                     'SVGFETurbulenceElement', 'SVGFETileElement', 'SVGFESpotLightElement',
                                     'SVGFESpecularLightingElement', 'SVGFEPointLightElement', 'SVGFEOffsetElement',
                                     'SVGFEMorphologyElement', 'SVGFEMergeNodeElement', 'SVGFEMergeElement',
                                     'SVGFEImageElement', 'SVGFEGaussianBlurElement', 'SVGFEFuncRElement',
                                     'SVGFEFuncGElement', 'SVGFEFuncBElement', 'SVGFEFuncAElement', 'SVGFEFloodElement',
                                     'SVGFEDropShadowElement', 'SVGFEDistantLightElement',
                                     'SVGFEDisplacementMapElement', 'SVGFEDiffuseLightingElement',
                                     'SVGFEConvolveMatrixElement', 'SVGFECompositeElement',
                                     'SVGFEComponentTransferElement', 'SVGFEColorMatrixElement', 'SVGFEBlendElement',
                                     'SVGEllipseElement', 'SVGElement', 'SVGDescElement', 'SVGDefsElement',
                                     'SVGComponentTransferFunctionElement', 'SVGClipPathElement', 'SVGCircleElement',
                                     'SVGAnimationElement', 'SVGAnimatedTransformList', 'SVGAnimatedString',
                                     'SVGAnimatedRect', 'SVGAnimatedPreserveAspectRatio', 'SVGAnimatedNumberList',
                                     'SVGAnimatedNumber', 'SVGAnimatedLengthList', 'SVGAnimatedLength',
                                     'SVGAnimatedInteger', 'SVGAnimatedEnumeration', 'SVGAnimatedBoolean',
                                     'SVGAnimatedAngle', 'SVGAnimateTransformElement', 'SVGAnimateMotionElement',
                                     'SVGAnimateElement', 'SVGAngle', 'SVGAElement', 'Response', 'ResizeObserverSize',
                                     'ResizeObserverEntry', 'ResizeObserver', 'Request', 'ReportingObserver',
                                     'ReportBody', 'ReadableStreamDefaultReader', 'ReadableStreamDefaultController',
                                     'ReadableStreamBYOBRequest', 'ReadableStreamBYOBReader', 'ReadableStream',
                                     'ReadableByteStreamController', 'Range', 'RadioNodeList', 'RTCTrackEvent',
                                     'RTCStatsReport', 'RTCSessionDescription', 'RTCSctpTransport', 'RTCRtpTransceiver',
                                     'RTCRtpSender', 'RTCRtpReceiver', 'RTCPeerConnectionIceEvent',
                                     'RTCPeerConnectionIceErrorEvent', 'RTCPeerConnection', 'RTCIceTransport',
                                     'RTCIceCandidate', 'RTCErrorEvent', 'RTCError', 'RTCEncodedVideoFrame',
                                     'RTCEncodedAudioFrame', 'RTCDtlsTransport', 'RTCDataChannelEvent',
                                     'RTCDTMFToneChangeEvent', 'RTCDTMFSender', 'RTCCertificate',
                                     'PromiseRejectionEvent', 'ProgressEvent', 'ProcessingInstruction', 'PopStateEvent',
                                     'PointerEvent', 'PluginArray', 'Plugin', 'PictureInPictureWindow',
                                     'PictureInPictureEvent', 'Permissions', 'PermissionStatus', 'PeriodicWave',
                                     'PerformanceTiming', 'PerformanceServerTiming', 'PerformanceScriptTiming',
                                     'PerformanceResourceTiming', 'PerformancePaintTiming',
                                     'PerformanceObserverEntryList', 'PerformanceObserver',
                                     'PerformanceNavigationTiming', 'PerformanceNavigation', 'PerformanceMeasure',
                                     'PerformanceMark', 'PerformanceLongTaskTiming',
                                     'PerformanceLongAnimationFrameTiming', 'PerformanceEventTiming',
                                     'PerformanceEntry', 'PerformanceElementTiming', 'Performance', 'Path2D',
                                     'PannerNode', 'PageTransitionEvent', 'OverconstrainedError', 'OscillatorNode',
                                     'OffscreenCanvasRenderingContext2D', 'OffscreenCanvas', 'OfflineAudioContext',
                                     'OfflineAudioCompletionEvent', 'Observable', 'NodeList', 'NodeIterator',
                                     'NodeFilter', 'Node', 'NetworkInformation', 'NavigatorUAData', 'Navigator',
                                     'NavigationTransition', 'NavigationPrecommitController', 'NavigationHistoryEntry',
                                     'NavigationDestination', 'NavigationCurrentEntryChangeEvent',
                                     'NavigationActivation', 'Navigation', 'NavigateEvent', 'NamedNodeMap',
                                     'MutationRecord', 'MutationObserver', 'MouseEvent', 'MimeTypeArray', 'MimeType',
                                     'MessagePort', 'MessageEvent', 'MessageChannel', 'MediaStreamTrackVideoStats',
                                     'MediaStreamTrackProcessor', 'MediaStreamTrackGenerator', 'MediaStreamTrackEvent',
                                     'MediaStreamTrackAudioStats', 'MediaStreamTrack', 'MediaStreamEvent',
                                     'MediaStreamAudioSourceNode', 'MediaStreamAudioDestinationNode', 'MediaStream',
                                     'MediaSourceHandle', 'MediaSource', 'MediaRecorder', 'MediaQueryListEvent',
                                     'MediaQueryList', 'MediaList', 'MediaError', 'MediaEncryptedEvent',
                                     'MediaElementAudioSourceNode', 'MediaCapabilities', 'MathMLElement', 'Location',
                                     'LayoutShiftAttribution', 'LayoutShift', 'LargestContentfulPaint',
                                     'KeyframeEffect', 'KeyboardEvent', 'IntersectionObserverEntry',
                                     'IntersectionObserver', 'InterestEvent', 'InputEvent', 'InputDeviceInfo',
                                     'InputDeviceCapabilities', 'Ink', 'ImageData', 'ImageBitmapRenderingContext',
                                     'ImageBitmap', 'IdleDeadline', 'IIRFilterNode', 'IDBVersionChangeEvent',
                                     'IDBTransaction', 'IDBRequest', 'IDBRecord', 'IDBOpenDBRequest', 'IDBObjectStore',
                                     'IDBKeyRange', 'IDBIndex', 'IDBFactory', 'IDBDatabase', 'IDBCursorWithValue',
                                     'IDBCursor', 'History', 'HighlightRegistry', 'Highlight', 'Headers',
                                     'HashChangeEvent', 'HTMLVideoElement', 'HTMLUnknownElement', 'HTMLUListElement',
                                     'HTMLTrackElement', 'HTMLTitleElement', 'HTMLTimeElement', 'HTMLTextAreaElement',
                                     'HTMLTemplateElement', 'HTMLTableSectionElement', 'HTMLTableRowElement',
                                     'HTMLTableElement', 'HTMLTableColElement', 'HTMLTableCellElement',
                                     'HTMLTableCaptionElement', 'HTMLStyleElement', 'HTMLSpanElement',
                                     'HTMLSourceElement', 'HTMLSlotElement', 'HTMLSelectedContentElement',
                                     'HTMLSelectElement', 'HTMLScriptElement', 'HTMLQuoteElement',
                                     'HTMLProgressElement', 'HTMLPreElement', 'HTMLPictureElement', 'HTMLParamElement',
                                     'HTMLParagraphElement', 'HTMLOutputElement', 'HTMLOptionsCollection',
                                     'HTMLOptionElement', 'HTMLOptGroupElement', 'HTMLObjectElement',
                                     'HTMLOListElement', 'HTMLModElement', 'HTMLMeterElement', 'HTMLMetaElement',
                                     'HTMLMenuElement', 'HTMLMediaElement', 'HTMLMarqueeElement', 'HTMLMapElement',
                                     'HTMLLinkElement', 'HTMLLegendElement', 'HTMLLabelElement', 'HTMLLIElement',
                                     'HTMLInputElement', 'HTMLImageElement', 'HTMLIFrameElement', 'HTMLHtmlElement',
                                     'HTMLHeadingElement', 'HTMLHeadElement', 'HTMLHRElement', 'HTMLFrameSetElement',
                                     'HTMLFrameElement', 'HTMLFormElement', 'HTMLFormControlsCollection',
                                     'HTMLFontElement', 'HTMLFieldSetElement', 'HTMLEmbedElement', 'HTMLElement',
                                     'HTMLDocument', 'HTMLDivElement', 'HTMLDirectoryElement', 'HTMLDialogElement',
                                     'HTMLDetailsElement', 'HTMLDataListElement', 'HTMLDataElement', 'HTMLDListElement',
                                     'HTMLCollection', 'HTMLCanvasElement', 'HTMLButtonElement', 'HTMLBodyElement',
                                     'HTMLBaseElement', 'HTMLBRElement', 'HTMLAudioElement', 'HTMLAreaElement',
                                     'HTMLAnchorElement', 'HTMLAllCollection', 'GeolocationPositionError',
                                     'GeolocationPosition', 'GeolocationCoordinates', 'Geolocation',
                                     'GamepadHapticActuator', 'GamepadEvent', 'GamepadButton', 'Gamepad', 'GainNode',
                                     'FormDataEvent', 'FormData', 'FontFaceSetLoadEvent', 'FontFaceSet', 'FontFace',
                                     'FocusEvent', 'FileReader', 'FileList', 'File', 'FeaturePolicy', 'External',
                                     'EventTarget', 'EventSource', 'EventCounts', 'Event', 'ErrorEvent',
                                     'EncodedVideoChunk', 'EncodedAudioChunk', 'ElementInternals', 'Element',
                                     'EditContext', 'DynamicsCompressorNode', 'DragEvent', 'DocumentType',
                                     'DocumentTimeline', 'DocumentFragment', 'Document', 'DelegatedInkTrailPresenter',
                                     'DelayNode', 'DecompressionStream', 'DataTransferItemList', 'DataTransferItem',
                                     'DataTransfer', 'DOMTokenList', 'DOMStringMap', 'DOMStringList', 'DOMRectReadOnly',
                                     'DOMRectList', 'DOMRect', 'DOMQuad', 'DOMPointReadOnly', 'DOMPoint', 'DOMParser',
                                     'DOMMatrixReadOnly', 'DOMMatrix', 'DOMImplementation', 'DOMException', 'DOMError',
                                     'CustomStateSet', 'CustomEvent', 'CustomElementRegistry', 'Crypto',
                                     'CountQueuingStrategy', 'ConvolverNode', 'ContentVisibilityAutoStateChangeEvent',
                                     'ConstantSourceNode', 'CompressionStream', 'CompositionEvent', 'Comment',
                                     'CommandEvent', 'CloseWatcher', 'CloseEvent', 'ClipboardEvent', 'CharacterData',
                                     'CharacterBoundsUpdateEvent', 'ChannelSplitterNode', 'ChannelMergerNode',
                                     'CaretPosition', 'CanvasRenderingContext2D', 'CanvasPattern', 'CanvasGradient',
                                     'CanvasCaptureMediaStreamTrack', 'CSSViewTransitionRule',
                                     'CSSVariableReferenceValue', 'CSSUnparsedValue', 'CSSUnitValue', 'CSSTranslate',
                                     'CSSTransition', 'CSSTransformValue', 'CSSTransformComponent', 'CSSSupportsRule',
                                     'CSSStyleValue', 'CSSStyleSheet', 'CSSStyleRule', 'CSSStyleDeclaration',
                                     'CSSStartingStyleRule', 'CSSSkewY', 'CSSSkewX', 'CSSSkew', 'CSSScopeRule',
                                     'CSSScale', 'CSSRuleList', 'CSSRule', 'CSSRotate', 'CSSPropertyRule',
                                     'CSSPositionValue', 'CSSPositionTryRule', 'CSSPositionTryDescriptors',
                                     'CSSPerspective', 'CSSPageRule', 'CSSNumericValue', 'CSSNumericArray',
                                     'CSSNestedDeclarations', 'CSSNamespaceRule', 'CSSMediaRule', 'CSSMatrixComponent',
                                     'CSSMathValue', 'CSSMathSum', 'CSSMathProduct', 'CSSMathNegate', 'CSSMathMin',
                                     'CSSMathMax', 'CSSMathInvert', 'CSSMathClamp', 'CSSMarginRule',
                                     'CSSLayerStatementRule', 'CSSLayerBlockRule', 'CSSKeywordValue',
                                     'CSSKeyframesRule', 'CSSKeyframeRule', 'CSSImportRule', 'CSSImageValue',
                                     'CSSGroupingRule', 'CSSFontPaletteValuesRule', 'CSSFontFaceRule',
                                     'CSSCounterStyleRule', 'CSSContainerRule', 'CSSConditionRule', 'CSSAnimation',
                                     'CSS', 'CSPViolationReportBody', 'CDATASection', 'ByteLengthQueuingStrategy',
                                     'BrowserCaptureMediaStreamTrack', 'BroadcastChannel', 'BlobEvent', 'Blob',
                                     'BiquadFilterNode', 'BeforeUnloadEvent', 'BeforeInstallPromptEvent',
                                     'BaseAudioContext', 'BarProp', 'AudioWorkletNode', 'AudioSinkInfo',
                                     'AudioScheduledSourceNode', 'AudioProcessingEvent', 'AudioParamMap', 'AudioParam',
                                     'AudioNode', 'AudioListener', 'AudioDestinationNode', 'AudioData', 'AudioContext',
                                     'AudioBufferSourceNode', 'AudioBuffer', 'Attr', 'AnimationTimeline',
                                     'AnimationPlaybackEvent', 'AnimationEvent', 'AnimationEffect', 'Animation',
                                     'AnalyserNode', 'AbstractRange', 'AbortSignal', 'AbortController', 'window',
                                     'self', 'document', 'name', 'location', 'customElements', 'history', 'navigation',
                                     'locationbar', 'menubar', 'personalbar', 'scrollbars', 'statusbar', 'toolbar',
                                     'status', 'closed', 'frames', 'length', 'top', 'opener', 'parent', 'frameElement',
                                     'navigator', 'origin', 'external', 'screen', 'innerWidth', 'innerHeight',
                                     'scrollX', 'pageXOffset', 'scrollY', 'pageYOffset', 'visualViewport', 'screenX',
                                     'screenY', 'outerWidth', 'outerHeight', 'devicePixelRatio', 'event',
                                     'clientInformation', 'offscreenBuffering', 'screenLeft', 'screenTop', 'styleMedia',
                                     'onsearch', 'onappinstalled', 'onbeforeinstallprompt', 'onabort', 'onbeforeinput',
                                     'onbeforematch', 'onbeforetoggle', 'onblur', 'oncancel', 'oncanplay',
                                     'oncanplaythrough', 'onchange', 'onclick', 'onclose', 'oncommand',
                                     'oncontentvisibilityautostatechange', 'oncontextlost', 'oncontextmenu',
                                     'oncontextrestored', 'oncuechange', 'ondblclick', 'ondrag', 'ondragend',
                                     'ondragenter', 'ondragleave', 'ondragover', 'ondragstart', 'ondrop',
                                     'ondurationchange', 'onemptied', 'onended', 'onerror', 'onfocus', 'onformdata',
                                     'oninput', 'oninvalid', 'onkeydown', 'onkeypress', 'onkeyup', 'onload',
                                     'onloadeddata', 'onloadedmetadata', 'onloadstart', 'onmousedown', 'onmouseenter',
                                     'onmouseleave', 'onmousemove', 'onmouseout', 'onmouseover', 'onmouseup',
                                     'onmousewheel', 'onpause', 'onplay', 'onplaying', 'onprogress', 'onratechange',
                                     'onreset', 'onresize', 'onscroll', 'onscrollend', 'onsecuritypolicyviolation',
                                     'onseeked', 'onseeking', 'onselect', 'onslotchange', 'onstalled', 'onsubmit',
                                     'onsuspend', 'ontimeupdate', 'ontoggle', 'onvolumechange', 'onwaiting',
                                     'onwebkitanimationend', 'onwebkitanimationiteration', 'onwebkitanimationstart',
                                     'onwebkittransitionend', 'onwheel', 'onauxclick', 'ongotpointercapture',
                                     'onlostpointercapture', 'onpointerdown', 'onpointermove', 'onpointerup',
                                     'onpointercancel', 'onpointerover', 'onpointerout', 'onpointerenter',
                                     'onpointerleave', 'onselectstart', 'onselectionchange', 'onanimationcancel',
                                     'onanimationend', 'onanimationiteration', 'onanimationstart', 'ontransitionrun',
                                     'ontransitionstart', 'ontransitionend', 'ontransitioncancel', 'onbeforexrselect',
                                     'onafterprint', 'onbeforeprint', 'onbeforeunload', 'onhashchange',
                                     'onlanguagechange', 'onmessage', 'onmessageerror', 'onoffline', 'ononline',
                                     'onpagehide', 'onpageshow', 'onpopstate', 'onrejectionhandled', 'onstorage',
                                     'onunhandledrejection', 'onunload', 'isSecureContext', 'crossOriginIsolated',
                                     'scheduler', 'performance', 'trustedTypes', 'crypto', 'indexedDB', 'localStorage',
                                     'sessionStorage', 'alert', 'atob', 'blur', 'btoa', 'cancelAnimationFrame',
                                     'cancelIdleCallback', 'captureEvents', 'clearInterval', 'clearTimeout', 'close',
                                     'confirm', 'createImageBitmap', 'fetch', 'find', 'focus', 'getComputedStyle',
                                     'getSelection', 'matchMedia', 'moveBy', 'moveTo', 'open', 'postMessage', 'print',
                                     'prompt', 'queueMicrotask', 'releaseEvents', 'reportError',
                                     'requestAnimationFrame', 'requestIdleCallback', 'resizeBy', 'resizeTo', 'scroll',
                                     'scrollBy', 'scrollTo', 'setInterval', 'setTimeout', 'stop', 'structuredClone',
                                     'webkitCancelAnimationFrame', 'webkitRequestAnimationFrame', 'Temporal',
                                     'SuppressedError', 'DisposableStack', 'AsyncDisposableStack', 'Float16Array',
                                     'chrome', 'WebAssembly', 'crashReport', 'cookieStore', 'ondevicemotion',
                                     'ondeviceorientation', 'ondeviceorientationabsolute', 'onpointerrawupdate',
                                     'caches', 'documentPictureInPicture', 'sharedStorage', 'AbsoluteOrientationSensor',
                                     'Accelerometer', 'AudioDecoder', 'AudioEncoder', 'AudioWorklet', 'BatteryManager',
                                     'Cache', 'CacheStorage', 'Clipboard', 'ClipboardChangeEvent', 'ClipboardItem',
                                     'CookieChangeEvent', 'CookieStore', 'CookieStoreManager', 'CreateMonitor',
                                     'Credential', 'CredentialsContainer', 'CryptoKey', 'DeviceMotionEvent',
                                     'DeviceMotionEventAcceleration', 'DeviceMotionEventRotationRate',
                                     'DeviceOrientationEvent', 'FederatedCredential', 'GPU', 'GPUAdapter',
                                     'GPUAdapterInfo', 'GPUBindGroup', 'GPUBindGroupLayout', 'GPUBuffer',
                                     'GPUBufferUsage', 'GPUCanvasContext', 'GPUColorWrite', 'GPUCommandBuffer',
                                     'GPUCommandEncoder', 'GPUCompilationInfo', 'GPUCompilationMessage',
                                     'GPUComputePassEncoder', 'GPUComputePipeline', 'GPUDevice', 'GPUDeviceLostInfo',
                                     'GPUError', 'GPUExternalTexture', 'GPUInternalError', 'GPUMapMode',
                                     'GPUOutOfMemoryError', 'GPUPipelineError', 'GPUPipelineLayout', 'GPUQuerySet',
                                     'GPUQueue', 'GPURenderBundle', 'GPURenderBundleEncoder', 'GPURenderPassEncoder',
                                     'GPURenderPipeline', 'GPUSampler', 'GPUShaderModule', 'GPUShaderStage',
                                     'GPUSupportedFeatures', 'GPUSupportedLimits', 'GPUTexture', 'GPUTextureUsage',
                                     'GPUTextureView', 'GPUUncapturedErrorEvent', 'GPUValidationError', 'GravitySensor',
                                     'Gyroscope', 'IdleDetector', 'ImageCapture', 'ImageDecoder', 'ImageTrack',
                                     'ImageTrackList', 'Keyboard', 'KeyboardLayoutMap', 'LinearAccelerationSensor',
                                     'MIDIAccess', 'MIDIConnectionEvent', 'MIDIInput', 'MIDIInputMap',
                                     'MIDIMessageEvent', 'MIDIOutput', 'MIDIOutputMap', 'MIDIPort', 'MediaDeviceInfo',
                                     'MediaDevices', 'MediaKeyMessageEvent', 'MediaKeySession', 'MediaKeyStatusMap',
                                     'MediaKeySystemAccess', 'MediaKeys', 'NavigationPreloadManager',
                                     'NavigatorManagedData', 'OrientationSensor', 'PasswordCredential',
                                     'ProtectedAudience', 'RelativeOrientationSensor', 'ScreenDetailed',
                                     'ScreenDetails', 'Sensor', 'SensorErrorEvent', 'ServiceWorkerRegistration',
                                     'StorageManager', 'SubtleCrypto', 'VideoDecoder', 'VideoEncoder',
                                     'VirtualKeyboard', 'WGSLLanguageFeatures', 'WebTransport',
                                     'WebTransportBidirectionalStream', 'WebTransportDatagramDuplexStream',
                                     'WebTransportError', 'Worklet', 'XRDOMOverlayState', 'XRLayer', 'XRWebGLBinding',
                                     'AudioPlaybackStats', 'AuthenticatorAssertionResponse',
                                     'AuthenticatorAttestationResponse', 'AuthenticatorResponse', 'PublicKeyCredential',
                                     'Bluetooth', 'BluetoothCharacteristicProperties', 'BluetoothDevice',
                                     'BluetoothRemoteGATTCharacteristic', 'BluetoothRemoteGATTDescriptor',
                                     'BluetoothRemoteGATTServer', 'BluetoothRemoteGATTService', 'CaptureController',
                                     'CrashReportContext', 'DevicePosture', 'DigitalCredential',
                                     'DocumentPictureInPicture', 'EyeDropper', 'FetchLaterResult',
                                     'FileSystemDirectoryHandle', 'FileSystemFileHandle', 'FileSystemHandle',
                                     'FileSystemWritableFileStream', 'FileSystemObserver', 'FontData',
                                     'FragmentDirective', 'HID', 'HIDConnectionEvent', 'HIDDevice',
                                     'HIDInputReportEvent', 'IdentityCredential', 'IdentityCredentialError',
                                     'IdentityProvider', 'NavigatorLogin', 'LanguageDetector', 'Lock', 'LockManager',
                                     'ServiceWorker', 'ServiceWorkerContainer', 'NotRestoredReasonDetails',
                                     'NotRestoredReasons', 'OTPCredential', 'PaymentAddress', 'PaymentRequest',
                                     'PaymentRequestUpdateEvent', 'PaymentResponse', 'PaymentManager',
                                     'PaymentMethodChangeEvent', 'Presentation', 'PresentationAvailability',
                                     'PresentationConnection', 'PresentationConnectionAvailableEvent',
                                     'PresentationConnectionCloseEvent', 'PresentationConnectionList',
                                     'PresentationReceiver', 'PresentationRequest', 'PressureObserver',
                                     'PressureRecord', 'Serial', 'SerialPort', 'SpeechRecognitionPhrase',
                                     'StorageBucket', 'StorageBucketManager', 'Summarizer', 'Translator', 'USB',
                                     'USBAlternateInterface', 'USBConfiguration', 'USBConnectionEvent', 'USBDevice',
                                     'USBEndpoint', 'USBInTransferResult', 'USBInterface',
                                     'USBIsochronousInTransferPacket', 'USBIsochronousInTransferResult',
                                     'USBIsochronousOutTransferPacket', 'USBIsochronousOutTransferResult',
                                     'USBOutTransferResult', 'WakeLock', 'WakeLockSentinel', 'XRAnchor', 'XRAnchorSet',
                                     'XRBoundedReferenceSpace', 'XRCPUDepthInformation', 'XRCamera',
                                     'XRDepthInformation', 'XRFrame', 'XRHand', 'XRHitTestResult', 'XRHitTestSource',
                                     'XRInputSource', 'XRInputSourceArray', 'XRInputSourceEvent',
                                     'XRInputSourcesChangeEvent', 'XRJointPose', 'XRJointSpace', 'XRLightEstimate',
                                     'XRLightProbe', 'XRPose', 'XRRay', 'XRReferenceSpace', 'XRReferenceSpaceEvent',
                                     'XRRenderState', 'XRRigidTransform', 'XRSession', 'XRSessionEvent', 'XRSpace',
                                     'XRSystem', 'XRTransientInputHitTestResult', 'XRTransientInputHitTestSource',
                                     'XRView', 'XRViewerPose', 'XRViewport', 'XRWebGLDepthInformation', 'XRWebGLLayer',
                                     'XRCompositionLayer', 'XRProjectionLayer', 'XRCubeLayer', 'XRCylinderLayer',
                                     'XREquirectLayer', 'XRLayerEvent', 'XRQuadLayer', 'XRSubImage', 'XRWebGLSubImage',
                                     'XRPlane', 'XRPlaneSet', 'XRVisibilityMaskChangeEvent', 'fetchLater',
                                     'getDigitalGoodsService', 'getScreenDetails', 'queryLocalFonts',
                                     'showDirectoryPicker', 'showOpenFilePicker', 'showSaveFilePicker',
                                     'originAgentCluster', 'viewport', 'onpageswap', 'onpagereveal', 'credentialless',
                                     'fence', 'launchQueue', 'speechSynthesis', 'onscrollsnapchange',
                                     'onscrollsnapchanging', 'ongamepadconnected', 'ongamepaddisconnected',
                                     'AnimationTrigger', 'BackgroundFetchManager', 'BackgroundFetchRecord',
                                     'BackgroundFetchRegistration', 'BluetoothUUID', 'CSSFontFeatureValuesRule',
                                     'CSSFunctionDeclarations', 'CSSFunctionDescriptors', 'CSSFunctionRule',
                                     'CSSPseudoElement', 'ChapterInformation', 'CropTarget',
                                     'DocumentPictureInPictureEvent', 'Fence', 'FencedFrameConfig',
                                     'HTMLFencedFrameElement', 'HTMLGeolocationElement', 'HTMLUserMediaElement',
                                     'IntegrityViolationReportBody', 'InteractionContentfulPaint',
                                     'PerformanceSoftNavigation', 'LaunchParams', 'LaunchQueue', 'MediaMetadata',
                                     'MediaSession', 'Notification', 'Origin', 'PageRevealEvent', 'PageSwapEvent',
                                     'PerformanceTimingConfidence', 'PeriodicSyncManager', 'Profiler', 'PushManager',
                                     'PushSubscription', 'PushSubscriptionOptions', 'QuotaExceededError',
                                     'RTCDataChannel', 'RTCRtpScriptTransform', 'RemotePlayback', 'RestrictionTarget',
                                     'Sanitizer', 'SharedStorage', 'SharedStorageWorklet', 'SharedStorageAppendMethod',
                                     'SharedStorageClearMethod', 'SharedStorageDeleteMethod',
                                     'SharedStorageModifierMethod', 'SharedStorageSetMethod', 'SharedWorker',
                                     'SnapEvent', 'SpeechGrammar', 'SpeechGrammarList', 'SpeechRecognition',
                                     'SpeechRecognitionErrorEvent', 'SpeechRecognitionEvent', 'SpeechSynthesis',
                                     'SpeechSynthesisErrorEvent', 'SpeechSynthesisEvent', 'SpeechSynthesisUtterance',
                                     'SpeechSynthesisVoice', 'TimelineTrigger', 'TimelineTriggerRange',
                                     'TimelineTriggerRangeList', 'Viewport', 'WebSocketError', 'WebSocketStream',
                                     'XSLTProcessor', 'webkitSpeechGrammar', 'webkitSpeechGrammarList',
                                     'webkitSpeechRecognition', 'webkitSpeechRecognitionError',
                                     'webkitSpeechRecognitionEvent', 'webkitRequestFileSystem',
                                     'webkitResolveLocalFileSystemURL', 'webpackChunk_N_E', '__next_set_public_path__',
                                     'next', '__NEXT_DATA__', '__SSG_MANIFEST_CB', '__NEXT_P', '_N_E',
                                     'applyFocusVisiblePolyfill', '__MIDDLEWARE_MATCHERS', '__BUILD_MANIFEST',
                                     '__SSG_MANIFEST', '_tsdk', 'captchaFoxOnLoad', '__core-js_shared__', '__svelte',
                                     'captchafox', '_0x5e41', '__cf_wapi', '_0x30fc', 'TEMPORARY', 'PERSISTENT',
                                     'constructor', 'addEventListener', 'dispatchEvent', 'removeEventListener', 'when',
                                     'constructor'],
                          'CF0131': ['location', '_reactListeningnnvo2fss20q', 'constructor', 'implementation', 'URL',
                                     'documentURI', 'compatMode', 'characterSet', 'charset', 'inputEncoding',
                                     'contentType', 'doctype', 'documentElement', 'xmlEncoding', 'xmlVersion',
                                     'xmlStandalone', 'domain', 'referrer', 'cookie', 'lastModified', 'readyState',
                                     'title', 'dir', 'body', 'head', 'images', 'embeds', 'plugins', 'links', 'forms',
                                     'scripts', 'currentScript', 'defaultView', 'designMode', 'onreadystatechange',
                                     'anchors', 'applets', 'fgColor', 'linkColor', 'vlinkColor', 'alinkColor',
                                     'bgColor', 'all', 'scrollingElement', 'onpointerlockchange', 'onpointerlockerror',
                                     'hidden', 'visibilityState', 'wasDiscarded', 'prerendering', 'featurePolicy',
                                     'webkitVisibilityState', 'webkitHidden', 'onbeforecopy', 'onbeforecut',
                                     'onbeforepaste', 'onfreeze', 'onprerenderingchange', 'onresume', 'onsearch',
                                     'onvisibilitychange', 'timeline', 'fullscreenEnabled', 'fullscreen',
                                     'onfullscreenchange', 'onfullscreenerror', 'webkitIsFullScreen',
                                     'webkitCurrentFullScreenElement', 'webkitFullscreenEnabled',
                                     'webkitFullscreenElement', 'onwebkitfullscreenchange', 'onwebkitfullscreenerror',
                                     'rootElement', 'pictureInPictureEnabled', 'onabort', 'onbeforeinput',
                                     'onbeforematch', 'onbeforetoggle', 'onblur', 'oncancel', 'oncanplay',
                                     'oncanplaythrough', 'onchange', 'onclick', 'onclose', 'oncommand',
                                     'oncontentvisibilityautostatechange', 'oncontextlost', 'oncontextmenu',
                                     'oncontextrestored', 'oncuechange', 'ondblclick', 'ondrag', 'ondragend',
                                     'ondragenter', 'ondragleave', 'ondragover', 'ondragstart', 'ondrop',
                                     'ondurationchange', 'onemptied', 'onended', 'onerror', 'onfocus', 'onformdata',
                                     'oninput', 'oninvalid', 'onkeydown', 'onkeypress', 'onkeyup', 'onload',
                                     'onloadeddata', 'onloadedmetadata', 'onloadstart', 'onmousedown', 'onmouseenter',
                                     'onmouseleave', 'onmousemove', 'onmouseout', 'onmouseover', 'onmouseup',
                                     'onmousewheel', 'onpause', 'onplay', 'onplaying', 'onprogress', 'onratechange',
                                     'onreset', 'onresize', 'onscroll', 'onscrollend', 'onsecuritypolicyviolation',
                                     'onseeked', 'onseeking', 'onselect', 'onslotchange', 'onstalled', 'onsubmit',
                                     'onsuspend', 'ontimeupdate', 'ontoggle', 'onvolumechange', 'onwaiting',
                                     'onwebkitanimationend', 'onwebkitanimationiteration', 'onwebkitanimationstart',
                                     'onwebkittransitionend', 'onwheel', 'onauxclick', 'ongotpointercapture',
                                     'onlostpointercapture', 'onpointerdown', 'onpointermove', 'onpointerup',
                                     'onpointercancel', 'onpointerover', 'onpointerout', 'onpointerenter',
                                     'onpointerleave', 'onselectstart', 'onselectionchange', 'onanimationcancel',
                                     'onanimationend', 'onanimationiteration', 'onanimationstart', 'ontransitionrun',
                                     'ontransitionstart', 'ontransitionend', 'ontransitioncancel', 'onbeforexrselect',
                                     'oncopy', 'oncut', 'onpaste', 'children', 'firstElementChild', 'lastElementChild',
                                     'childElementCount', 'activeElement', 'styleSheets', 'pointerLockElement',
                                     'fullscreenElement', 'adoptedStyleSheets', 'pictureInPictureElement', 'fonts',
                                     'adoptNode', 'append', 'captureEvents', 'caretPositionFromPoint',
                                     'caretRangeFromPoint', 'clear', 'close', 'createAttribute', 'createAttributeNS',
                                     'createCDATASection', 'createComment', 'createDocumentFragment', 'createElement',
                                     'createElementNS', 'createEvent', 'createExpression', 'createNSResolver',
                                     'createNodeIterator', 'createProcessingInstruction', 'createRange',
                                     'createTextNode', 'createTreeWalker', 'elementFromPoint', 'elementsFromPoint',
                                     'evaluate', 'execCommand', 'exitFullscreen', 'exitPictureInPicture',
                                     'exitPointerLock', 'getAnimations', 'getElementById', 'getElementsByClassName',
                                     'getElementsByName', 'getElementsByTagName', 'getElementsByTagNameNS',
                                     'getSelection', 'hasFocus', 'hasStorageAccess', 'hasUnpartitionedCookieAccess',
                                     'importNode', 'moveBefore', 'open', 'prepend', 'queryCommandEnabled',
                                     'queryCommandIndeterm', 'queryCommandState', 'queryCommandSupported',
                                     'queryCommandValue', 'querySelector', 'querySelectorAll', 'releaseEvents',
                                     'replaceChildren', 'requestStorageAccess', 'requestStorageAccessFor',
                                     'startViewTransition', 'webkitCancelFullScreen', 'webkitExitFullscreen', 'write',
                                     'writeln', 'constructor', 'fragmentDirective', 'onpointerrawupdate',
                                     'browsingTopics', 'hasPrivateToken', 'hasRedemptionRecord', 'activeViewTransition',
                                     'onscrollsnapchange', 'onscrollsnapchanging', 'customElementRegistry',
                                     'ariaNotify', 'nodeType', 'nodeName', 'baseURI', 'isConnected', 'ownerDocument',
                                     'parentNode', 'parentElement', 'childNodes', 'firstChild', 'lastChild',
                                     'previousSibling', 'nextSibling', 'nodeValue', 'textContent', 'ELEMENT_NODE',
                                     'ATTRIBUTE_NODE', 'TEXT_NODE', 'CDATA_SECTION_NODE', 'ENTITY_REFERENCE_NODE',
                                     'ENTITY_NODE', 'PROCESSING_INSTRUCTION_NODE', 'COMMENT_NODE', 'DOCUMENT_NODE',
                                     'DOCUMENT_TYPE_NODE', 'DOCUMENT_FRAGMENT_NODE', 'NOTATION_NODE',
                                     'DOCUMENT_POSITION_DISCONNECTED', 'DOCUMENT_POSITION_PRECEDING',
                                     'DOCUMENT_POSITION_FOLLOWING', 'DOCUMENT_POSITION_CONTAINS',
                                     'DOCUMENT_POSITION_CONTAINED_BY', 'DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC',
                                     'appendChild', 'cloneNode', 'compareDocumentPosition', 'contains', 'getRootNode',
                                     'hasChildNodes', 'insertBefore', 'isDefaultNamespace', 'isEqualNode', 'isSameNode',
                                     'lookupNamespaceURI', 'lookupPrefix', 'normalize', 'removeChild', 'replaceChild',
                                     'constructor', 'addEventListener', 'dispatchEvent', 'removeEventListener', 'when',
                                     'constructor'],
                          'CF0132': ['vendorSub', 'productSub', 'vendor', 'maxTouchPoints', 'scheduling',
                                     'userActivation', 'geolocation', 'doNotTrack', 'webkitTemporaryStorage',
                                     'webkitPersistentStorage', 'windowControlsOverlay', 'hardwareConcurrency',
                                     'cookieEnabled', 'appCodeName', 'appName', 'appVersion', 'platform', 'product',
                                     'userAgent', 'language', 'languages', 'onLine', 'webdriver', 'plugins',
                                     'mimeTypes', 'pdfViewerEnabled', 'connection', 'getGamepads', 'javaEnabled',
                                     'sendBeacon', 'vibrate', 'constructor', 'deprecatedRunAdAuctionEnforcesKAnonymity',
                                     'protectedAudience', 'bluetooth', 'clipboard', 'credentials', 'keyboard',
                                     'managed', 'mediaDevices', 'serviceWorker', 'virtualKeyboard', 'wakeLock',
                                     'deviceMemory', 'userAgentData', 'locks', 'storage', 'gpu', 'login', 'ink',
                                     'mediaCapabilities', 'permissions', 'devicePosture', 'hid', 'mediaSession',
                                     'presentation', 'serial', 'usb', 'xr', 'storageBuckets', 'adAuctionComponents',
                                     'runAdAuction', 'canLoadAdAuctionFencedFrame', 'canShare', 'share',
                                     'clearAppBadge', 'getBattery', 'getUserMedia', 'requestMIDIAccess',
                                     'requestMediaKeySystemAccess', 'setAppBadge', 'webkitGetUserMedia',
                                     'clearOriginJoinedAdInterestGroups', 'createAuctionNonce', 'joinAdInterestGroup',
                                     'leaveAdInterestGroup', 'updateAdInterestGroups', 'deprecatedReplaceInURN',
                                     'deprecatedURNToURL', 'getInstalledRelatedApps', 'getInterestGroupAdAuctionData',
                                     'registerProtocolHandler', 'unregisterProtocolHandler'],
                          'CF0133': ['lang', 'class', 'data-js-focus-visible'], 'CF0134': 'object', 'CF0135': False,
                          'CF0136': 33, 'CF0137': False, 'CF0138': False, 'CF0139': False, 'CF0140': False,
                          'CF0141': False, 'CF0142': True, 'CF0143': True, 'CF0144': [True, True],
                          'CF0145': '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0',
                          'CF0146': False, 'CF0147': False, 'CF0148': 'https://captchafox.com/'},
                   'host': 'captchafox.com',
                   'k': self.k,
                   'type': 'slide'
        }

        cap_cry = CapFoxCrypt()
        payload = cap_cry.encoder(fp_json)
        logger.debug(f"[solver_challenge running] k: {self.k}")
        logger.debug(f"[solver_challenge running] payload hex: {CapFoxCrypt.encoder_to_hex(payload)}")

        headers = {
            'User-Agent': self.user_agent,
            'accept-language': "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
            'cache-control': "no-cache",
            'content-type': "text/plain",
            'origin': "https://portal.captchafox.com",
            'pragma': "no-cache",
            'priority': "u=1, i",
            'referer': "https://portal.captchafox.com/",
            'sec-ch-ua': "\"Not=A?Brand\";v=\"99\", \"Microsoft Edge\";v=\"151\", \"Chromium\";v=\"151\"",
            'sec-ch-ua-mobile': "?0",
            'sec-ch-ua-platform': "\"Windows\"",
            'sec-fetch-dest': "empty",
            'sec-fetch-mode': "cors",
            'sec-fetch-site': "same-site",
            'x-pulse': self.pulse
        }

        try:

            response = requests.post(
                f"https://api.captchafox.com/captcha/{self.site_key}/challenge",
                data=payload,
                headers=headers,
                proxies=self.proxy
            )
            resp_json = response.json()
            logger.debug(f"[solver_challenge running] resp_json: {resp_json}")
            solver_status = resp_json.get("solved","")
            if solver_status:
                token = resp_json.get("token","")
                logger.success(f"[solver_challenge running] challenge solver success token: {token}")
            else:
                logger.warning(f"[solver_challenge running] challenge solver fail")

        except Exception as e:
            logger.error(f"[solver_challenge except] error info: {e}")

if __name__ == '__main__':
    cfox = CaptchaFox(
        "sk_WTsTCEH6Kswd_Y5Lmhe2eMARiBTJoScs",
        "https://portal.captchafox.com/register"
    )
    cfox.get_config()
    cfox.solver_challenge()